<!DOCTYPE html>
<html lang="en" dir="ltr"><head>
  
                           
     


<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="generator" content="Hugo 0.81.0" />
<title>Disclosure Risk for Student Microdata | Shaina Trevino</title>


<meta property="twitter:site" content="@apreshill">
<meta property="twitter:creator" content="@apreshill">







  
    
  
<meta name="description" content="This blog post walks through one example of reducing disclosure risk for student microdata under FERPA. Specifically, assessing re-identification risk and applying statistical disclosure control for a simulated, student data set with the sdcMicro R package">


<meta property="og:site_name" content="Shaina Trevino">
<meta property="og:title" content="Disclosure Risk for Student Microdata | Shaina Trevino">
<meta property="og:description" content="This blog post walks through one example of reducing disclosure risk for student microdata under FERPA. Specifically, assessing re-identification risk and applying statistical disclosure control for a simulated, student data set with the sdcMicro R package" />
<meta property="og:type" content="page" />
<meta property="og:url" content="https://shaina-trevino.netlify.app/blog/2021-3-16-disclosure-risk-rmarkdown/" />
<meta property="og:locale" content="en">




    
        <meta property="og:image" content="https://shaina-trevino.netlify.app/blog/sidebar-listing-old.jpg" >
        <meta property="twitter:card" content="summary_large_image">
        <meta name="twitter:image" content="https://shaina-trevino.netlify.app/blog/sidebar-listing-old.jpg" >
    
    
  <meta itemprop="name" content="Disclosure Risk for Student Microdata">
<meta itemprop="description" content="Overview   Under the Family Educational Rights and Privacy Act (FERPA), schools can release data to researchers without parent or student consent if the data is released under a FERPA study exception with a data sharing agreement or if the data has been properly de-identified. Proper data de-identification involves removing or altering all personally identifiable information (PII) from the data to minimize the disclosure risk of individuals."><meta itemprop="datePublished" content="2021-03-16T00:00:00&#43;00:00" />
<meta itemprop="dateModified" content="2021-03-16T00:00:00&#43;00:00" />
<meta itemprop="wordCount" content="10788">
<meta itemprop="keywords" content="" />
  
  <!--[if IE]><script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
  <link rel="shortcut icon" href="/img/favicon.ico" type="image/x-icon">
  <link rel="icon" href="/img/favicon.ico" type="image/x-icon">
  
  
  <link rel="stylesheet" href="/style.main.min.b5827680c871c01d16d126f1d6f70d518257e0ee28936aeaae0bc2bf6a57f431.css" integrity="sha256-tYJ2gMhxwB0W0Sbx1vcNUYJX4O4ok2rqrgvCv2pX9DE=" media="screen">
  
  
  <script src="/panelset.min.d74e921a1b9af2d938fdff19e433ba539cdb202961eddae2356a54199f0653ec.js" type="text/javascript"></script>
  
  
  <script src="/main.min.206b76eb47404da6ed29595a105309ae3bd2d6f694a0e530efa9aa1acb0dbfa8.js" type="text/javascript"></script>
</head>
<body>
      <div class="grid-container single">
<header class="site-header pt4 pb2 mb4 bb b--transparent ph5 headroom z-max" role="banner">
  <nav class="site-nav db dt-l w-100" role="navigation">
    <a class="site-brand db dtc-l v-mid link no-underline w-100 w-33-l tc tl-l" href="https://shaina-trevino.netlify.app/" title="Home">
      <img src="/img/blogophonic-mark-dark.png" class="dib db-l h2 w-auto" alt="Shaina Trevino">
    </a>
    <div class="site-links db dtc-l v-mid w-100 w-47-l tc tr-l mt3 mt0-l ttu tracked">
      
        
        
        
      <a class="link f6 f5-l dib pv1 ph2 " href="/publications/" title="Publications">Publications</a>
      
        
        
        
      <a class="link f6 f5-l dib pv1 ph2 active" href="/blog/" title="Blog">Blog</a>
      
      
    </div>
  </nav>
</header>

<main class="page-main pa4" role="main">
  <section class="page-content mw7 center">
    <article class="post-content pa0 ph4-l">
      <header class="post-header">
        <h1 class="f1 lh-solid measure-narrow mb3 fw4">Disclosure Risk for Student Microdata</h1>
        
        <p class="f6 measure lh-copy mv1">By Shaina Trevino</p>
        <p class="f7 db mv0 ttu">March 16, 2021</p>

      

      </header>
      <section class="post-body pt5 pb4">
        <script src="https://shaina-trevino.netlify.app/blog/2021-3-16-disclosure-risk-rmarkdown/index_files/kePrint/kePrint.js"></script>
<link href="https://shaina-trevino.netlify.app/blog/2021-3-16-disclosure-risk-rmarkdown/index_files/lightable/lightable.css" rel="stylesheet" />
<script src="https://shaina-trevino.netlify.app/blog/2021-3-16-disclosure-risk-rmarkdown/index_files/kePrint/kePrint.js"></script>
<link href="https://shaina-trevino.netlify.app/blog/2021-3-16-disclosure-risk-rmarkdown/index_files/lightable/lightable.css" rel="stylesheet" />
<script src="https://shaina-trevino.netlify.app/blog/2021-3-16-disclosure-risk-rmarkdown/index_files/kePrint/kePrint.js"></script>
<link href="https://shaina-trevino.netlify.app/blog/2021-3-16-disclosure-risk-rmarkdown/index_files/lightable/lightable.css" rel="stylesheet" />
<script src="https://shaina-trevino.netlify.app/blog/2021-3-16-disclosure-risk-rmarkdown/index_files/kePrint/kePrint.js"></script>
<link href="https://shaina-trevino.netlify.app/blog/2021-3-16-disclosure-risk-rmarkdown/index_files/lightable/lightable.css" rel="stylesheet" />
<script src="https://shaina-trevino.netlify.app/blog/2021-3-16-disclosure-risk-rmarkdown/index_files/kePrint/kePrint.js"></script>
<link href="https://shaina-trevino.netlify.app/blog/2021-3-16-disclosure-risk-rmarkdown/index_files/lightable/lightable.css" rel="stylesheet" />
<script src="https://shaina-trevino.netlify.app/blog/2021-3-16-disclosure-risk-rmarkdown/index_files/kePrint/kePrint.js"></script>
<link href="https://shaina-trevino.netlify.app/blog/2021-3-16-disclosure-risk-rmarkdown/index_files/lightable/lightable.css" rel="stylesheet" />
<script src="https://shaina-trevino.netlify.app/blog/2021-3-16-disclosure-risk-rmarkdown/index_files/kePrint/kePrint.js"></script>
<link href="https://shaina-trevino.netlify.app/blog/2021-3-16-disclosure-risk-rmarkdown/index_files/lightable/lightable.css" rel="stylesheet" />
<script src="https://shaina-trevino.netlify.app/blog/2021-3-16-disclosure-risk-rmarkdown/index_files/kePrint/kePrint.js"></script>
<link href="https://shaina-trevino.netlify.app/blog/2021-3-16-disclosure-risk-rmarkdown/index_files/lightable/lightable.css" rel="stylesheet" />
<script src="https://shaina-trevino.netlify.app/blog/2021-3-16-disclosure-risk-rmarkdown/index_files/kePrint/kePrint.js"></script>
<link href="https://shaina-trevino.netlify.app/blog/2021-3-16-disclosure-risk-rmarkdown/index_files/lightable/lightable.css" rel="stylesheet" />
<script src="https://shaina-trevino.netlify.app/blog/2021-3-16-disclosure-risk-rmarkdown/index_files/kePrint/kePrint.js"></script>
<link href="https://shaina-trevino.netlify.app/blog/2021-3-16-disclosure-risk-rmarkdown/index_files/lightable/lightable.css" rel="stylesheet" />
<script src="https://shaina-trevino.netlify.app/blog/2021-3-16-disclosure-risk-rmarkdown/index_files/kePrint/kePrint.js"></script>
<link href="https://shaina-trevino.netlify.app/blog/2021-3-16-disclosure-risk-rmarkdown/index_files/lightable/lightable.css" rel="stylesheet" />
<script src="https://shaina-trevino.netlify.app/blog/2021-3-16-disclosure-risk-rmarkdown/index_files/kePrint/kePrint.js"></script>
<link href="https://shaina-trevino.netlify.app/blog/2021-3-16-disclosure-risk-rmarkdown/index_files/lightable/lightable.css" rel="stylesheet" />
<script src="https://shaina-trevino.netlify.app/blog/2021-3-16-disclosure-risk-rmarkdown/index_files/kePrint/kePrint.js"></script>
<link href="https://shaina-trevino.netlify.app/blog/2021-3-16-disclosure-risk-rmarkdown/index_files/lightable/lightable.css" rel="stylesheet" />
<script src="https://shaina-trevino.netlify.app/blog/2021-3-16-disclosure-risk-rmarkdown/index_files/kePrint/kePrint.js"></script>
<link href="https://shaina-trevino.netlify.app/blog/2021-3-16-disclosure-risk-rmarkdown/index_files/lightable/lightable.css" rel="stylesheet" />




<h1 id="overview">Overview
  <a href="#overview"></a>
</h1>
<p>Under the Family Educational Rights and Privacy Act (FERPA), schools can release data to researchers without parent or student consent if the data is released under a 
<a href="https://studentprivacy.ed.gov/sites/default/files/resource_document/file/FERPA%20Exceptions_HANDOUT_portrait.pdf" target="_blank" rel="noopener">FERPA study exception</a> with a data sharing agreement or if the data has been properly de-identified. Proper data de-identification involves removing or altering all personally identifiable information (PII) from the data to minimize the disclosure risk of individuals. It is important to note that PII includes not only the obvious identifiable information about individuals (e.g., direct identifiers; names, student IDs, social security number, date of birth, address), but also any other information that can be used to identify an individual alone or in combination with other information that can be linked to the data (i.e., indirect identifiers). Thus, simply removing direct identifiers does not properly de-identify the data. Careful attention must be payed to the identification and altering of indirect identifiers to adequately reduce disclosure risk.</p>
<p>A disclosure occurs when an intruder can reveal the identity of an individual in the data set or learn confidential information about them. Thus, measuring disclosure risk involves calculating risk metrics related to an intruder&rsquo;s ability to identify individuals (i.e., re-identification risk). After assessing the re-identification risk of the original data, statistical disclosure control techniques can be applied to reduce disclosure risk to an appropriate level. There are no specific guidelines or methods to properly de-identify data because the re-identification risk varies depending on the structure, context, and purpose of the data. There may also be other federal, state, or local laws that require different levels of de-identification.</p>
<p>For our purposes, we will be walking through the process of statistical disclosure control under FERPA with cross-sectional, student-level micro-data (i.e., one student per row). However, it is important to note that there are certain characteristics of micro-data files that can increase the likelihood of a disclosure (we only need to attend to the first):</p>
<ul>
<li>
<p>Existence of rare or detailed records (e.g., unique characteristics or extreme values)</p>
</li>
<li>
<p>Multilevel structure (i.e., if one level is too detailed, disclosure at other levels could be possible)</p>
</li>
<li>
<p>Linking to external sources (e.g., rare combinations of variables, shared linking keys)</p>
</li>
<li>
<p>Longitudinal structure (i.e., adding records over time could increase disclosure risk)</p>
</li>
<li>
<p>Census data (i.e., if an intruder knows who is in the data, disclosure is more likely)</p>
</li>
</ul>
<p>Specifically, this blog will explain the basic steps of assessing disclosure risk and applying statistical disclosure control techniques with the <code>{sdcMicro}</code> package and briefly mention how to re-assess disclosure risk and data utility after transformation when releasing FERPA-compliant student micro-data. Code and data available on 
<a href="https://github.com/shainatrevino/Professional-Website" target="_blank" rel="noopener">GitHub</a></p>




<h2 id="data-description">Data Description
  <a href="#data-description"><svg class="anchor-symbol" aria-hidden="true" height="26" width="26" viewBox="0 0 22 22" xmlns="http://www.w3.org/2000/svg">
      <path d="M0 0h24v24H0z" fill="currentColor"></path>
      <path d="M3.9 12c0-1.71 1.39-3.1 3.1-3.1h4V7H7c-2.76.0-5 2.24-5 5s2.24 5 5 5h4v-1.9H7c-1.71.0-3.1-1.39-3.1-3.1zM8 13h8v-2H8v2zm9-6h-4v1.9h4c1.71.0 3.1 1.39 3.1 3.1s-1.39 3.1-3.1 3.1h-4V17h4c2.76.0 5-2.24 5-5s-2.24-5-5-5z"></path>
    </svg></a>
</h2>
<p>This data set was simulated to represent the distributions of administrative student variables that a researcher would potentially request access to. Thus, distributions and descriptive statistics represent a student population, however, relationships (e.g., correlations) among variables are not representative, nor realistic, and should not be interpreted.</p>
<p>When possible, the variables selected for de-identification and release should be limited to those necessary for data analysis in order to minimize disclosure risk and maximize data utility. Our data set includes a sample of 25,000 students and 13 variables including:</p>
<ul>
<li>
<p><code>id</code>: study-specific randomized ID number for each student</p>
</li>
<li>
<p><code>grade_level</code>: student&rsquo;s grade level</p>
</li>
<li>
<p><code>sex</code>: student sex</p>
</li>
<li>
<p><code>race</code>: student race/ethnicity</p>
</li>
<li>
<p><code>gpa</code>: student&rsquo;s unweighted grade point averages</p>
</li>
<li>
<p><code>econ_dis</code>: student flagged as economically disadvantaged</p>
</li>
<li>
<p><code>disability</code>: student flagged with a disability (i.e., individual education plan)</p>
</li>
<li>
<p><code>dis_cat</code>: student disability type</p>
</li>
<li>
<p><code>lang</code>: student first language</p>
</li>
<li>
<p><code>iss_off</code>: count of behavior incidents that resulted in in-school suspension</p>
</li>
<li>
<p><code>iss_days</code>: total number of days served in in-school suspension</p>
</li>
<li>
<p><code>subj_off</code>: count of behavior incidents that were classified as subjective (i.e., subjective to interpretation)</p>
</li>
<li>
<p><code>days_absent</code>: total number of days absent</p>
</li>
</ul>
<p>We will use the <code>import()</code> and <code>here()</code> function to import our data and tidy it with the <code>{tidyverse}</code> package (e.g., modifying character variables to factors and defining missing values). It is important to verify that all variables are classified correctly (e.g., numeric or factor) and missing values are defined as <code>NA</code>.</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">sim_df <span style="color:#000;font-weight:bold">&lt;-</span> rio<span style="color:#000;font-weight:bold">::</span><span style="color:#900;font-weight:bold">import</span>(here<span style="color:#000;font-weight:bold">::</span><span style="color:#900;font-weight:bold">here</span>(<span style="color:#d14">&#34;content/data&#34;</span>, <span style="color:#d14">&#34;sim_df.csv&#34;</span>)) <span style="color:#000;font-weight:bold">%&gt;%</span> <span style="color:#998;font-style:italic">#import data</span>
  <span style="color:#900;font-weight:bold">mutate_if</span>(is.character, as.factor) <span style="color:#000;font-weight:bold">%&gt;%</span> <span style="color:#998;font-style:italic">#transform characters to factors</span>
  <span style="color:#900;font-weight:bold">mutate_all</span>(na_if, <span style="color:#d14">&#34;&#34;</span>) <span style="color:#998;font-style:italic">#transform blank cells to missing</span>

<span style="color:#998;font-style:italic">#use str() to view variables and types</span>
<span style="color:#900;font-weight:bold">str</span>(sim_df)
</code></pre></div><pre><code>## 'data.frame':	25000 obs. of  13 variables:
##  $ id         : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ grade_level: Factor w/ 14 levels &quot;10th Grade&quot;,&quot;11th Grade&quot;,..: 1 8 12 12 9 7 5 11 7 4 ...
##  $ sex        : Factor w/ 3 levels &quot;&quot;,&quot;Female&quot;,&quot;Male&quot;: 2 3 2 3 3 3 3 2 3 3 ...
##  $ race       : Factor w/ 9 levels &quot;&quot;,&quot;Asian&quot;,&quot;Black&quot;,..: 9 4 4 9 9 9 9 4 9 4 ...
##  $ gpa        : num  2 3 2.33 2.33 2.67 3.33 2.67 3 3 2.67 ...
##  $ econ_dis   : Factor w/ 2 levels &quot;No&quot;,&quot;Yes&quot;: 2 1 2 1 1 2 1 1 1 1 ...
##  $ disability : Factor w/ 2 levels &quot;No&quot;,&quot;Yes&quot;: 1 1 2 1 2 1 1 1 1 1 ...
##  $ dis_cat    : Factor w/ 8 levels &quot;Autism&quot;,&quot;Developmental Delay&quot;,..: 5 5 7 5 7 5 5 5 5 5 ...
##  $ lang       : Factor w/ 9 levels &quot;Arabic&quot;,&quot;Chinese&quot;,..: 3 3 7 3 3 3 3 7 3 3 ...
##  $ iss_off    : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ iss_days   : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ subj_off   : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ days_absent: int  2 0 2 0 4 3 3 0 1 0 ...
</code></pre>



<h1 id="preprocessing">Preprocessing
  <a href="#preprocessing"></a>
</h1>
<p>Before beginning the disclosure risk assessment, some decisions need to be made about the data and types of risks to be protecting against. Direct identifiers should also be removed or obscured from the data in this step as disclosure risk assessment and control procedures are concerned with protecting indirect identifiers.</p>




<h2 id="understand-the-data-and-context">Understand the Data and Context
  <a href="#understand-the-data-and-context"><svg class="anchor-symbol" aria-hidden="true" height="26" width="26" viewBox="0 0 22 22" xmlns="http://www.w3.org/2000/svg">
      <path d="M0 0h24v24H0z" fill="currentColor"></path>
      <path d="M3.9 12c0-1.71 1.39-3.1 3.1-3.1h4V7H7c-2.76.0-5 2.24-5 5s2.24 5 5 5h4v-1.9H7c-1.71.0-3.1-1.39-3.1-3.1zM8 13h8v-2H8v2zm9-6h-4v1.9h4c1.71.0 3.1 1.39 3.1 3.1s-1.39 3.1-3.1 3.1h-4V17h4c2.76.0 5-2.24 5-5s-2.24-5-5-5z"></path>
    </svg></a>
</h2>
<p>It can be very helpful to explore the variables and relations among variables in your data set. Looking at the distributions will give a sense of which variables have rare values and are more risky. It will be necessary to fully understand the structure and distributions of variables when making decisions for applying appropriate statistical disclosure techniques.</p>
<p>It is also crucial to understand the context in which the data is going to be released as this can affect the de-identification process. For example, data shared under a strict data sharing agreement may need less protection and can have a higher acceptable disclosure risk compared to data that is shared without such agreements or will be widely shared.</p>
<p>Understanding the data and data context makes it possible to develop what are called &ldquo;motivated intruder scenarios.&rdquo; These intruder scenarios guide the types of protections that need to be applied to the data to appropriately reduce disclosure risk. To develop an intruder scenario, document the ways in which an individual in your data can be identified by an intruder. For example, our data includes many demographic variables, therefore an intruder could identify someone in our data set if they linked unique demographic variables with public registries that include identifiable information (e.g., voter registration, DMV records). Another scenario that is almost always present is the possibility of an inadvertent disclosure which can occur when there are unique combinations of demographic variables resulting in an accidental disclosure. Developing intruder scenarios can sometimes require the support of a subject matter expert to determine which auxiliary data sets are publicly available and contain similar information to the data set to be de-identified.</p>




<h2 id="selecting-key-variables-pii">Selecting Key Variables (PII)
  <a href="#selecting-key-variables-pii"><svg class="anchor-symbol" aria-hidden="true" height="26" width="26" viewBox="0 0 22 22" xmlns="http://www.w3.org/2000/svg">
      <path d="M0 0h24v24H0z" fill="currentColor"></path>
      <path d="M3.9 12c0-1.71 1.39-3.1 3.1-3.1h4V7H7c-2.76.0-5 2.24-5 5s2.24 5 5 5h4v-1.9H7c-1.71.0-3.1-1.39-3.1-3.1zM8 13h8v-2H8v2zm9-6h-4v1.9h4c1.71.0 3.1 1.39 3.1 3.1s-1.39 3.1-3.1 3.1h-4V17h4c2.76.0 5-2.24 5-5s-2.24-5-5-5z"></path>
    </svg></a>
</h2>
<p>Arguably,  one of the most challenging parts of proper data de-identification under FERPA is the classification indirect identifiers, also called key variables in the data de-identification literature or PII in FERPA. FERPA defines indirect identifiers as including &ldquo;information that, alone or in combination, is linked or linkable to a specific student that would allow a reasonable person in the school community, who does not have personal knowledge of the relevant circumstances, to identify the student with reasonable certainty&rdquo; (
<a href="https://www2.ed.gov/policy/gen/guid/fpco/pdf/ferparegs.pdf" target="_blank" rel="noopener">FERPA</a>, p. 6). This vague definition is the reason why classifying indirect identifiers can be so difficult.</p>
<p>Classifying variables as indirect identifiers or non-identifiers should include consideration of intruder scenarios, conceptual understanding of variables and potential linkages, and exploring variable risk alone and in combination with one another (e.g., rare values, small cell sizes). It can be helpful to assess disclosure risk multiple times with different sets of indirect identifiers or intruder scenarios to understand how different variables affect disclosure risk (e.g., higher re-identification risk, increased suppression) and may be indirect identifiers. For our purposes, we will assume that all variables can be linked with a specific student when combined with other variables in the data set (e.g., only one Asian female student with disability that speaks German). This is a very conservative approach that defines all &ldquo;real&rdquo; PII under FERPA correctly, but may classify non-PII variables as indirect identifiers and thus decrease the utility of the transformed data more than necessary. Often, data utility will decrease drastically the more number of indirect identifiers you define, however, more privacy protection is applied.</p>




<h1 id="disclosure-risk-assessment">Disclosure Risk Assessment
  <a href="#disclosure-risk-assessment"></a>
</h1>
<p>Once you understand your data, the environment for release, and the variables that are indirect identifiers, you can begin the process of assessing disclosure risk in your data set. To do this we will use the <code>{sdcMicro}</code> package and some functions from <code>{tidyverse}</code>.</p>




<h2 id="set-up-the-sdcmicro-object">Set up the <code>{sdcMicro}</code> Object
  <a href="#set-up-the-sdcmicro-object"><svg class="anchor-symbol" aria-hidden="true" height="26" width="26" viewBox="0 0 22 22" xmlns="http://www.w3.org/2000/svg">
      <path d="M0 0h24v24H0z" fill="currentColor"></path>
      <path d="M3.9 12c0-1.71 1.39-3.1 3.1-3.1h4V7H7c-2.76.0-5 2.24-5 5s2.24 5 5 5h4v-1.9H7c-1.71.0-3.1-1.39-3.1-3.1zM8 13h8v-2H8v2zm9-6h-4v1.9h4c1.71.0 3.1 1.39 3.1 3.1s-1.39 3.1-3.1 3.1h-4V17h4c2.76.0 5-2.24 5-5s-2.24-5-5-5z"></path>
    </svg></a>
</h2>
<p>The first step of disclosure risk analysis in <code>{sdcMicro}</code> is to create an object that tells <code>R</code> which continuous and categorical variables should be considered indirect identifiers in your data set. This is implemented with the <code>createSdcObj()</code> function (as shown below) which results in a <code>{sdcMicro}</code> object with many different layers (e.g., original data, transformed data, risk/utility metrics, and many other configuration settings). Mostly everything that we do to assess risk and de-identify data will involve manipulating this object. For this function, the <code>keyVars</code> refer to the categorical indirect identifiers and <code>numVars</code> are the continuous indirect identifiers.</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#998;font-style:italic">#create object</span>
initial_sdcobj <span style="color:#000;font-weight:bold">&lt;-</span> <span style="color:#900;font-weight:bold">createSdcObj</span>(dat <span style="color:#000;font-weight:bold">=</span> sim_df, <span style="color:#998;font-style:italic">#input data</span>
                               keyVars <span style="color:#000;font-weight:bold">=</span> <span style="color:#900;font-weight:bold">c</span>(<span style="color:#d14">&#34;grade_level&#34;</span>, <span style="color:#d14">&#34;sex&#34;</span>, <span style="color:#d14">&#34;race&#34;</span>, <span style="color:#d14">&#34;econ_dis&#34;</span>, 
                                           <span style="color:#d14">&#34;disability&#34;</span>, <span style="color:#d14">&#34;dis_cat&#34;</span>, <span style="color:#d14">&#34;lang&#34;</span>), <span style="color:#998;font-style:italic">#categorical</span>
                               numVars <span style="color:#000;font-weight:bold">=</span> <span style="color:#900;font-weight:bold">c</span>(<span style="color:#d14">&#34;gpa&#34;</span>, <span style="color:#d14">&#34;iss_off&#34;</span>, <span style="color:#d14">&#34;iss_days&#34;</span>, 
                                           <span style="color:#d14">&#34;subj_off&#34;</span>, <span style="color:#d14">&#34;days_absent&#34;</span>)) <span style="color:#998;font-style:italic">#continuous </span>
</code></pre></div><p>For our <code>{sdcMicro}</code> object, we specified our original data, the categorical indirect identifiers, and the continuous indirect identifiers. There are many other arguments that you can specify if needed (e.g., sampling weights, PRAM values) - just see the help documentation.</p>




<h2 id="categorical-variables-and-k-anonymity">Categorical Variables and <em>k</em>-anonymity
  <a href="#categorical-variables-and-k-anonymity"><svg class="anchor-symbol" aria-hidden="true" height="26" width="26" viewBox="0 0 22 22" xmlns="http://www.w3.org/2000/svg">
      <path d="M0 0h24v24H0z" fill="currentColor"></path>
      <path d="M3.9 12c0-1.71 1.39-3.1 3.1-3.1h4V7H7c-2.76.0-5 2.24-5 5s2.24 5 5 5h4v-1.9H7c-1.71.0-3.1-1.39-3.1-3.1zM8 13h8v-2H8v2zm9-6h-4v1.9h4c1.71.0 3.1 1.39 3.1 3.1s-1.39 3.1-3.1 3.1h-4V17h4c2.76.0 5-2.24 5-5s-2.24-5-5-5z"></path>
    </svg></a>
</h2>
<p>The methods for disclosure risk assessment and control differ for continuous vs. categorical variables (this is why they are defined separately in the object above). For categorical variables, disclosure risk can be assessed by calculating cross-tab frequency counts and the probability that an individual is unique or can be easily identified in the data set (e.g., small cell sizes). For this blog we will use the concept of <em>k</em>-anonymity to assess and control for disclosure risk of categorical variables.</p>
<p><em>k</em>-anonymity is a traditional privacy model that can be used to reduce re-identification risk. To achieve <em>k</em>-anonymity there needs to be at least <em>k</em> individuals with the same responses on all indirect identifiers for every combination of values in the indirect identifiers. The value of <em>k</em> should be specified in advance depending on a threshold for acceptable re-identification risk. For example, <em>k</em> = 2 means that there are no unique individuals in the data set since everyone will at least have 1 other individual with the same responses on all indirect identifiers and will not be distinguishable. However, the highest re-identification risk is still 50% since intruders have a 50/50 chance of identifying the correct individual when <em>k</em> = 2.</p>
<p>Alternatively, 5-anonymity will require at least 5 individuals to have the same responses on all variables and will have a highest re-identification risk of 20%. There are no specific guidelines for which <em>k</em> threshold to us. Statisticians have recommended a minimum <em>k</em> value of at least 3-5 for privacy preserving data publishing but determining the exact threshold should take into account local or state laws as well as the data environment for release. It may be necessary to select a higher threshold if the data will be publicly shared or archived (e.g., <em>k</em> = 10+).</p>
<p><em>k</em>-anonymity is best suited when assessing and controlling for population uniqueness. It can be used for sample uniqueness, but will often overestimate the re-identification risk unless sampling weights are included in the de-identification process. For a more detailed definition of sample vs. population uniqueness see 
<a href="http://www.ihsn.org/anonymization-risk-measure" target="_blank" rel="noopener">International Household Survey Network</a>. There were no sampling weights included in the <code>sdcMicro</code> object we created which means we are controlling for sample uniqueness assuming our sample of the student population. We will be using <em>k</em> = 5 for our threshold to release de-identified student data to a set of approved researchers under a data sharing agreement.</p>




<h3 id="k-anonymity-violations"><em>k</em>-anonymity Violations
  <a href="#k-anonymity-violations"><svg class="anchor-symbol" aria-hidden="true" height="26" width="26" viewBox="0 0 22 22" xmlns="http://www.w3.org/2000/svg">
      <path d="M0 0h24v24H0z" fill="currentColor"></path>
      <path d="M3.9 12c0-1.71 1.39-3.1 3.1-3.1h4V7H7c-2.76.0-5 2.24-5 5s2.24 5 5 5h4v-1.9H7c-1.71.0-3.1-1.39-3.1-3.1zM8 13h8v-2H8v2zm9-6h-4v1.9h4c1.71.0 3.1 1.39 3.1 3.1s-1.39 3.1-3.1 3.1h-4V17h4c2.76.0 5-2.24 5-5s-2.24-5-5-5z"></path>
    </svg></a>
</h3>
<p>One simple way to assess disclosure risk of categorical indirect identifiers is to calculate the number of observations in the data set that violate <em>k</em>-anonymity. In other words, the number of individuals with unique or risky (i.e., small cell size) responses. To view the number of individuals that violate <em>k</em>-anonymity for <em>k</em> = 2, 3, and 5, use <code>print()</code> on the <code>{sdcMicro}</code> object we created above:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#900;font-weight:bold">print</span>(initial_sdcobj)
</code></pre></div><pre><code>## Infos on 2/3-Anonymity:
## 
## Number of observations violating
##   - 2-anonymity: 1257 (5.028%)
##   - 3-anonymity: 2177 (8.708%)
##   - 5-anonymity: 3313 (13.252%)
## 
## ----------------------------------------------------------------------
</code></pre><p>The above output shows that about 5% of students are unique in the sample (i.e., violate 2-anonymity) and 13% of students are below our specified re-identification risk threshold (5-anonymity). To calculate the number of individuals violating <em>k</em>-anonymity at higher thresholds we can use the <code>kAnon_violations()</code> function:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">kvio <span style="color:#000;font-weight:bold">&lt;-</span> <span style="color:#900;font-weight:bold">kAnon_violations</span>(initial_sdcobj, <span style="color:#998;font-style:italic">#sdcMicro object</span>
                         weighted <span style="color:#000;font-weight:bold">=</span> <span style="color:#000;font-weight:bold">FALSE</span>, <span style="color:#998;font-style:italic">#no sampling weights</span>
                         k <span style="color:#000;font-weight:bold">=</span> <span style="color:#099">10</span>) <span style="color:#998;font-style:italic">#k value threshold</span>
<span style="color:#900;font-weight:bold">print</span>(kvio)
</code></pre></div><pre><code>## [1] 5395
</code></pre><p>The above shows the number of students violating 10-anonymity is 5395 (21.58%).</p>




<h3 id="global-risk">Global Risk
  <a href="#global-risk"><svg class="anchor-symbol" aria-hidden="true" height="26" width="26" viewBox="0 0 22 22" xmlns="http://www.w3.org/2000/svg">
      <path d="M0 0h24v24H0z" fill="currentColor"></path>
      <path d="M3.9 12c0-1.71 1.39-3.1 3.1-3.1h4V7H7c-2.76.0-5 2.24-5 5s2.24 5 5 5h4v-1.9H7c-1.71.0-3.1-1.39-3.1-3.1zM8 13h8v-2H8v2zm9-6h-4v1.9h4c1.71.0 3.1 1.39 3.1 3.1s-1.39 3.1-3.1 3.1h-4V17h4c2.76.0 5-2.24 5-5s-2.24-5-5-5z"></path>
    </svg></a>
</h3>
<p>Global risk refers to the average re-identification risk of the entire data set. It is calculated by aggregating all individual risk scores (described below). When we first created our <code>{sdcMicro}</code> object, global and individual risk metrics were calculated and stored within the <code>{sdcMicro}</code> object. To access it we <code>print()</code> the <code>&quot;risk&quot;</code> metric of our <code>{sdcMicro}</code> object:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#900;font-weight:bold">print</span>(initial_sdcobj, <span style="color:#d14">&#34;risk&#34;</span>)
</code></pre></div><pre><code>## Risk measures:
## 
## Number of observations with higher risk than the main part of the data: 5395
## Expected number of re-identifications: 2774.21 (11.10 %)
</code></pre><p>The global risk is 0.111, indicating that a motivated intruder could potentially identify 2774 (11.1%) of students , on average. This risk is very high, but is likely overestimated since we are not using sampling weights and thus assumes the intruder knows which individuals are included in the sample. The output also shows that 5395 students have individual risk metrics that are operating differently compared to the majority of individual risk metrics (e.g., lower or higher). I find this measure less helpful, but it is interesting that it is the same as the 10-anonymity violations we calculated. After applying statistical disclosure control methods, we expect to see the global risk metrics reduce - especially the expected number of re-identifications.</p>
<p>It is important to note that global risks should be not be given too much weight when assessing disclosure risk. Although global risk metrics are easy to compute, they are aggregate measures that don&rsquo;t take into account unique individuals in the data set. It is possible to have an acceptable global risk but still have unique or high risk individuals in the data set. Thus, investigating individual risk is important when assessing disclosure risk. We did this briefly when calculating <em>k</em>-anonymity violations, but will want to look at individual risk in more depth next.</p>




<h3 id="individual-risk-and-sample-frequenciesuniqueness">Individual Risk and Sample Frequencies/Uniqueness
  <a href="#individual-risk-and-sample-frequenciesuniqueness"><svg class="anchor-symbol" aria-hidden="true" height="26" width="26" viewBox="0 0 22 22" xmlns="http://www.w3.org/2000/svg">
      <path d="M0 0h24v24H0z" fill="currentColor"></path>
      <path d="M3.9 12c0-1.71 1.39-3.1 3.1-3.1h4V7H7c-2.76.0-5 2.24-5 5s2.24 5 5 5h4v-1.9H7c-1.71.0-3.1-1.39-3.1-3.1zM8 13h8v-2H8v2zm9-6h-4v1.9h4c1.71.0 3.1 1.39 3.1 3.1s-1.39 3.1-3.1 3.1h-4V17h4c2.76.0 5-2.24 5-5s-2.24-5-5-5z"></path>
    </svg></a>
</h3>
<p>Individual risk is directly related to <em>k</em>-anonymity and refers to the probability of correctly re-identifying each individual student. As mentioned above, an individual that is 2-anonymous (i.e., in an equivalence class of 2) will have an individual risk of .5 indicating an intruder has a 50% chance of identifying this student successfully, whereas a unique individual will have an individual risk of 1 (100%). Alternatively, when an individual has the same responses as many others in the data set, they will all have a lower individual re-identification risk.</p>
<p>Individual risk metrics were already calculated and stored when we created the initial <code>{sdcMicro}</code> object. To view the individual risk for each observation, we extract the risk metrics and frequency counts (i.e., number of individuals who have the same responses on all indirect identifiers) and combine them with the original data set.</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">ind_risk <span style="color:#000;font-weight:bold">&lt;-</span> <span style="color:#900;font-weight:bold">data.frame</span>(initial_sdcobj<span style="color:#000;font-weight:bold">@</span>risk<span style="color:#000;font-weight:bold">$</span>individual) <span style="color:#000;font-weight:bold">%&gt;%</span> <span style="color:#998;font-style:italic">#extract risk metrics</span>
  <span style="color:#900;font-weight:bold">select</span>(<span style="color:#000;font-weight:bold">-</span>Fk) <span style="color:#998;font-style:italic">#de-select population metric</span>

ind_risk_df <span style="color:#000;font-weight:bold">&lt;-</span> <span style="color:#900;font-weight:bold">cbind</span>(sim_df, ind_risk) <span style="color:#998;font-style:italic">#combine with data</span>

<span style="color:#900;font-weight:bold">head</span>(ind_risk_df, <span style="color:#099">10</span>)
</code></pre></div><pre><code>## # A tibble: 10 x 10
##       id grade_level sex   race  econ_dis disability dis_cat lang     risk    fk
##    &lt;int&gt; &lt;fct&gt;       &lt;fct&gt; &lt;fct&gt; &lt;fct&gt;    &lt;fct&gt;      &lt;fct&gt;   &lt;fct&gt;   &lt;dbl&gt; &lt;dbl&gt;
##  1     1 10th Grade  Fema~ White Yes      No         Not Ap~ Engl~ 0.00505   198
##  2     2 5th Grade   Male  Hisp~ No       No         Not Ap~ Engl~ 0.0185     54
##  3     3 9th Grade   Fema~ Hisp~ Yes      Yes        Specif~ Span~ 1           1
##  4     4 9th Grade   Male  White No       No         Not Ap~ Engl~ 0.00535   187
##  5     5 6th Grade   Male  White No       Yes        Specif~ Engl~ 0.143       7
##  6     6 4th Grade   Male  White Yes      No         Not Ap~ Engl~ 0.00568   176
##  7     7 2nd Grade   Male  White No       No         Not Ap~ Engl~ 0.00549   182
##  8     8 8th Grade   Fema~ Hisp~ No       No         Not Ap~ Span~ 0.0909     11
##  9     9 4th Grade   Male  White No       No         Not Ap~ Engl~ 0.00549   182
## 10    10 1st Grade   Male  Hisp~ No       No         Not Ap~ Engl~ 0.0208     48
</code></pre><p>This will give you a data frame that includes the individual risk metrics (<code>risk</code>) and frequency counts for that combination for responses (<code>fk</code>). For example, we can see the 3rd observation is unique (i.e., only one person has this combination of responses in the data set) and has a 100% individual re-identification risk, whereas the 1st observation shares the same responses with 198 other individuals resulting in low re-identification risk (0.5%).</p>
<p>It is important to note that missing values will affect the calculation of individual risk and frequency counts (<code>fk</code>). If there are missing values in a combination, the frequency count will include the count of all possible responses for the missing value. For example, the response [10th Grade, Female, White] may have a combined frequency (<code>fk</code>) of 198, and the response [10th Grade, Male, White&hellip;] <code>fk</code> = 189. However an individual a missing value for <code>sex</code> [10th Grade, NA, White&hellip;] would have a combined frequency of 387 (198 + 189) and a much higher individual risk metric. Thus, it is very important to make sure that missing values are not identifiable.</p>
<p>Observing the individual risk metrics for each student in the data can be helpful to see which individuals have unique responses (i.e., filter when <code>fk</code> = 1) or are under a certain threshold (e.g., 5-anonymity). However, it is often more useful to look at sample frequencies and risk for each combination of responses possible instead of for each student.</p>




<h4 id="risky-variable-response-combinations">Risky Variable Response Combinations
  <a href="#risky-variable-response-combinations"></a>
</h4>
<p>We will use various functions from the <code>{tidyverse}</code> package to aggregate the individual risk metrics for each variable response combination:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">var_combos <span style="color:#000;font-weight:bold">&lt;-</span> ind_risk_df <span style="color:#000;font-weight:bold">%&gt;%</span> 
  <span style="color:#900;font-weight:bold">select</span>(id, <span style="color:#900;font-weight:bold">where</span>(is.factor), risk, fk) <span style="color:#000;font-weight:bold">%&gt;%</span> <span style="color:#998;font-style:italic">#select variables</span>
  <span style="color:#900;font-weight:bold">group_by</span>(grade_level, sex, race, econ_dis, disability, dis_cat, lang) <span style="color:#000;font-weight:bold">%&gt;%</span>  <span style="color:#998;font-style:italic">#group by all responses</span>
  <span style="color:#900;font-weight:bold">summarize</span>(risk <span style="color:#000;font-weight:bold">=</span> <span style="color:#900;font-weight:bold">mean</span>(risk), <span style="color:#998;font-style:italic">#aggregate risk metrics</span>
            freq <span style="color:#000;font-weight:bold">=</span> <span style="color:#900;font-weight:bold">mean</span>(fk),
            .groups <span style="color:#000;font-weight:bold">=</span> <span style="color:#d14">&#34;keep&#34;</span>)

var_combos
</code></pre></div><pre><code>## # A tibble: 3,238 x 9
## # Groups:   grade_level, sex, race, econ_dis, disability, dis_cat, lang [3,238]
##    grade_level sex    race  econ_dis disability dis_cat       lang    risk  freq
##    &lt;fct&gt;       &lt;fct&gt;  &lt;fct&gt; &lt;fct&gt;    &lt;fct&gt;      &lt;fct&gt;         &lt;fct&gt;  &lt;dbl&gt; &lt;dbl&gt;
##  1 10th Grade  Female Asian No       No         Not Applicab~ Chin~ 1          1
##  2 10th Grade  Female Asian No       No         Not Applicab~ Engl~ 0.0909    11
##  3 10th Grade  Female Asian No       No         Not Applicab~ Other 1          1
##  4 10th Grade  Female Asian No       No         Not Applicab~ Span~ 0.25       4
##  5 10th Grade  Female Asian No       Yes        Other         Other 1          1
##  6 10th Grade  Female Asian No       Yes        Specific Lea~ Engl~ 1          1
##  7 10th Grade  Female Asian No       Yes        Specific Lea~ Other 1          1
##  8 10th Grade  Female Asian Yes      No         Not Applicab~ Engl~ 0.1       10
##  9 10th Grade  Female Asian Yes      No         Not Applicab~ Span~ 1          1
## 10 10th Grade  Female Asian Yes      Yes        Specific Lea~ Engl~ 0.333      3
## # ... with 3,228 more rows
</code></pre><p>The resulting data frame shows the 3,238 possible response combinations for our categorical indirect identifiers and the corresponding risk metrics. You can see that the first response combination is unique, whereas the second combination has 11 students with those responses.</p>
<p>Next, we can filter each combination to show us only the unique response combinations:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">uniq <span style="color:#000;font-weight:bold">&lt;-</span> var_combos <span style="color:#000;font-weight:bold">%&gt;%</span> 
  <span style="color:#900;font-weight:bold">filter</span>(freq <span style="color:#000;font-weight:bold">==</span> <span style="color:#099">1</span>)

uniq
</code></pre></div><pre><code>## # A tibble: 1,257 x 9
## # Groups:   grade_level, sex, race, econ_dis, disability, dis_cat, lang [1,257]
##    grade_level sex    race  econ_dis disability dis_cat        lang   risk  freq
##    &lt;fct&gt;       &lt;fct&gt;  &lt;fct&gt; &lt;fct&gt;    &lt;fct&gt;      &lt;fct&gt;          &lt;fct&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1 10th Grade  Female Asian No       No         Not Applicable Chin~     1     1
##  2 10th Grade  Female Asian No       No         Not Applicable Other     1     1
##  3 10th Grade  Female Asian No       Yes        Other          Other     1     1
##  4 10th Grade  Female Asian No       Yes        Specific Lear~ Engl~     1     1
##  5 10th Grade  Female Asian No       Yes        Specific Lear~ Other     1     1
##  6 10th Grade  Female Asian Yes      No         Not Applicable Span~     1     1
##  7 10th Grade  Female Black No       No         Not Applicable Russ~     1     1
##  8 10th Grade  Female Black No       Yes        Specific Lear~ Other     1     1
##  9 10th Grade  Female Black No       Yes        Speech/Langua~ Engl~     1     1
## 10 10th Grade  Female Black Yes      Yes        Autism         Engl~     1     1
## # ... with 1,247 more rows
</code></pre><p>We already know from calculating the <em>k</em>-anonymity violations above that there are 1,257 unique individual responses in our data set. However, it is helpful to explore the pattern of unique responses to see which variables or response options are leading to high re-identification risk.</p>
<p>It is useful to also filter variable response combinations for those that are under our threshold. Since we are using 5-anonymity as our privacy model, we filter for response combinations with less than 5 students:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#998;font-style:italic">#filter high risk</span>
risky <span style="color:#000;font-weight:bold">&lt;-</span> var_combos <span style="color:#000;font-weight:bold">%&gt;%</span> 
  <span style="color:#900;font-weight:bold">filter</span>(freq <span style="color:#000;font-weight:bold">&lt;</span> <span style="color:#099">5</span>)

risky
</code></pre></div><pre><code>## # A tibble: 2,179 x 9
## # Groups:   grade_level, sex, race, econ_dis, disability, dis_cat, lang [2,179]
##    grade_level sex    race  econ_dis disability dis_cat        lang   risk  freq
##    &lt;fct&gt;       &lt;fct&gt;  &lt;fct&gt; &lt;fct&gt;    &lt;fct&gt;      &lt;fct&gt;          &lt;fct&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1 10th Grade  Female Asian No       No         Not Applicable Chin~ 1         1
##  2 10th Grade  Female Asian No       No         Not Applicable Other 1         1
##  3 10th Grade  Female Asian No       No         Not Applicable Span~ 0.25      4
##  4 10th Grade  Female Asian No       Yes        Other          Other 1         1
##  5 10th Grade  Female Asian No       Yes        Specific Lear~ Engl~ 1         1
##  6 10th Grade  Female Asian No       Yes        Specific Lear~ Other 1         1
##  7 10th Grade  Female Asian Yes      No         Not Applicable Span~ 1         1
##  8 10th Grade  Female Asian Yes      Yes        Specific Lear~ Engl~ 0.333     3
##  9 10th Grade  Female Black No       No         Not Applicable Other 0.25      4
## 10 10th Grade  Female Black No       No         Not Applicable Russ~ 1         1
## # ... with 2,169 more rows
</code></pre><p>The resulting data frame shows the risk metrics for the 2,179 possible response combinations that are under our threshold. Similar to the above step, it can be helpful here to explore this data frame for patterns of risky responses to see if there are certain variables or response options that are most often leading to risky variable combinations.</p>




<h2 id="continuous-variables">Continuous Variables
  <a href="#continuous-variables"><svg class="anchor-symbol" aria-hidden="true" height="26" width="26" viewBox="0 0 22 22" xmlns="http://www.w3.org/2000/svg">
      <path d="M0 0h24v24H0z" fill="currentColor"></path>
      <path d="M3.9 12c0-1.71 1.39-3.1 3.1-3.1h4V7H7c-2.76.0-5 2.24-5 5s2.24 5 5 5h4v-1.9H7c-1.71.0-3.1-1.39-3.1-3.1zM8 13h8v-2H8v2zm9-6h-4v1.9h4c1.71.0 3.1 1.39 3.1 3.1s-1.39 3.1-3.1 3.1h-4V17h4c2.76.0 5-2.24 5-5s-2.24-5-5-5z"></path>
    </svg></a>
</h2>
<p>The concept of <em>k</em>-anonymity and uniqueness often does not apply when measuring risk of continuous variables since continuous variables can have infinite values and would make most individuals unique when looking at frequencies of combined variables responses. For continuous variables, disclosure risk is often measured with probabilistic or distance-based metrics and by exploring outliers. While exploring distributions and outliers can give you a sense of the amount of risk (e.g., skewness) in continuous variables, probabilistic and distance-based risk metrics have to be calculated after applying statistical disclosure control techniques because they compare the transformed data to the raw data to assess re-identification risk.</p>
<p>Two distance-based risk metrics are calculate when using <code>{sdcMicro}</code>: record linkage and interval measures. Both metrics are based on similarity or uniqueness among transformed values and how close those values are to the original values (e.g., in the same neighborhood of values). Thus, these measures are most useful when using statistical disclosure techniques that alter the true data values (i.e., perturbative methods), such as adding statistical noise to variables. As discussed in later sections, we will not be using perturbative methods which makes these distance-based metrics less useful in our case. The calculation of these risk metrics are discussed in later sections after applying disclosure control methods.</p>
<p>To assess risk of our continuous variables before applying de-identification techniques, we will explore the distributions of our continuous variables and look for rare values.</p>




<h4 id="explore-distributions">Explore distributions
  <a href="#explore-distributions"></a>
</h4>
<p>To plot basic frequency distributions of our continuous variables we can use the <code>hist()</code> function for each continuous variable in our original data set (<code>sim_df</code>), such as for <code>gpa</code>:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#998;font-style:italic">#plot for gpa from original data</span>
<span style="color:#900;font-weight:bold">hist</span>(sim_df<span style="color:#000;font-weight:bold">$</span>gpa)
</code></pre></div><p><img src="https://shaina-trevino.netlify.app/blog/2021-3-16-disclosure-risk-rmarkdown/index_files/figure-html/gpa-render-1.png" width="672" /></p>
<p>We can do the same for all other continuous variables:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#998;font-style:italic">#plot each continuous variable </span>
<span style="color:#900;font-weight:bold">hist</span>(sim_df<span style="color:#000;font-weight:bold">$</span>iss_off)
<span style="color:#900;font-weight:bold">hist</span>(sim_df<span style="color:#000;font-weight:bold">$</span>iss_days)
<span style="color:#900;font-weight:bold">hist</span>(sim_df<span style="color:#000;font-weight:bold">$</span>subj_off)
<span style="color:#900;font-weight:bold">hist</span>(sim_df<span style="color:#000;font-weight:bold">$</span>days_absent)
</code></pre></div><p><img src="https://shaina-trevino.netlify.app/blog/2021-3-16-disclosure-risk-rmarkdown/index_files/figure-html/plot-cont-render-1.png" width="864" /></p>
<p>These plots show that <code>gpa</code> is the only variable with a normal distribution, whereas the three discipline variables (e.g., <code>iss_off</code>, <code>iss_days</code> and <code>subj_off</code>) and <code>days_absent</code> are highly skewed and thus have a higher re-identification risk. It also seems that <code>gpa</code> has already been truncated and could be considered a categorical variable and assessed with <em>k</em>-anonymity or grouped into intervals. The discipline variables are so skewed that it is hard to see the values of the tails. Will we want to look at these distributions in more detail, especially the values in the tails to help determine how much protection (i.e., top/bottom coding) we should apply to reduce re-identification risk.</p>




<h3 id="explore-tails-for-rare-values">Explore Tails for Rare Values
  <a href="#explore-tails-for-rare-values"><svg class="anchor-symbol" aria-hidden="true" height="26" width="26" viewBox="0 0 22 22" xmlns="http://www.w3.org/2000/svg">
      <path d="M0 0h24v24H0z" fill="currentColor"></path>
      <path d="M3.9 12c0-1.71 1.39-3.1 3.1-3.1h4V7H7c-2.76.0-5 2.24-5 5s2.24 5 5 5h4v-1.9H7c-1.71.0-3.1-1.39-3.1-3.1zM8 13h8v-2H8v2zm9-6h-4v1.9h4c1.71.0 3.1 1.39 3.1 3.1s-1.39 3.1-3.1 3.1h-4V17h4c2.76.0 5-2.24 5-5s-2.24-5-5-5z"></path>
    </svg></a>
</h3>
<p>When there are only a few individuals with high values for a variable, such as for our discipline values above, the potential for re-identification is high. Thus, it is helpful to understand which values of continuous variables are rare responses. Exploring the tails of distributions can help detect outliers and threshold values (i.e., a value in which any response above or below leads to rare values). This can be done by examining frequency tables for continuous variables, but those can be cumbersome to look through especially when there is a large range. We will use the <code>quantile()</code> function to calculate values that represent different percentiles of the sample (e.g., values of top 10%) in addition to looking at frequency tables to explore rare values.</p>
<p>The first continuous variable is <code>gpa</code> which does have a normal distribution. Therefore, we will want to look at the values in both tails (i.e., top and bottom percentiles). We can calculate the values based on default quantiles in this case (e.g., 25%, 50%, and 75% percentiles):</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#998;font-style:italic">#percentiles</span>
<span style="color:#900;font-weight:bold">quantile</span>(sim_df<span style="color:#000;font-weight:bold">$</span>gpa, <span style="color:#900;font-weight:bold">c</span>(<span style="color:#099">0</span>, <span style="color:#099">.25</span>, <span style="color:#099">.5</span>, <span style="color:#099">.75</span>, <span style="color:#099">1</span>), na.rm <span style="color:#000;font-weight:bold">=</span> <span style="color:#000;font-weight:bold">TRUE</span>) 
</code></pre></div><pre><code>##   0%  25%  50%  75% 100% 
## 1.00 2.33 2.67 3.00 4.00
</code></pre><p>The output shows that the range of <code>gpa</code> values is 1 - 4, the bottom 25% of students have a GPA of 2.33 or lower, and the top 25% of students have a GPA of 3.00 or higher. If possible, it is useful to determine a percentile threshold in advance in which values above/below that threshold will be considered risky. Then, you can calculate those percentiles specifically to see which/how many individuals have responses beyond that threshold. This will also help when determining how much protection to apply when using statistical disclosure control techniques. However, thresholds are often very difficult to determine and should consider the type of data release, sample size, skewness, and all intruder/disclosure scenarios discussed in previous sections.</p>
<p>Since <code>gpa</code> seems to already be aggregated (i.e., not truly continuous) and has such a small range, it will likely be more helpful to look at the frequency table for <code>gpa</code> instead of calculating different percentiles - especially since we do not have <em>apriori</em> thresholds. We can calculate basic frequency tables with the <code>table()</code> function:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#998;font-style:italic">#frequency table</span>
<span style="color:#900;font-weight:bold">table</span>(sim_df<span style="color:#000;font-weight:bold">$</span>gpa)
</code></pre></div><table class="table" style="width: auto !important; ">
 <thead>
  <tr>
   <th style="text-align:right;"> 1 </th>
   <th style="text-align:right;"> 1.33 </th>
   <th style="text-align:right;"> 1.67 </th>
   <th style="text-align:right;"> 2 </th>
   <th style="text-align:right;"> 2.33 </th>
   <th style="text-align:right;"> 2.67 </th>
   <th style="text-align:right;"> 3 </th>
   <th style="text-align:right;"> 3.33 </th>
   <th style="text-align:right;"> 3.67 </th>
   <th style="text-align:right;"> 4 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 37 </td>
   <td style="text-align:right;"> 283 </td>
   <td style="text-align:right;"> 2011 </td>
   <td style="text-align:right;"> 4037 </td>
   <td style="text-align:right;"> 6281 </td>
   <td style="text-align:right;"> 7779 </td>
   <td style="text-align:right;"> 3123 </td>
   <td style="text-align:right;"> 1139 </td>
   <td style="text-align:right;"> 305 </td>
  </tr>
</tbody>
</table>
<p>The frequency table shows that the bottom three values (1, 1.33, and 1.67) and the highest value (4.0) have significantly less responses compared to the middle values, and that values below 1.67 have a very high re-identification risk (less than .01% of sample). The table also confirms that <code>gpa</code> has already been aggregated from its continuous form and could be considered less risky because exact responses cannot be known with 100% certainty since we do not know the rounding rules applied.</p>
<p>Since the other continuous variables are highly skewed, it makes more sense to calculate percentiles for the tail of the distributions. For our second variable, <code>iss_off</code>, we will calculate values for the top 80+ percentiles and view the top 95+ percentiles with more granularity:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#998;font-style:italic">#in school suspensions percentiles</span>
<span style="color:#900;font-weight:bold">quantile</span>(sim_df<span style="color:#000;font-weight:bold">$</span>iss_off, <span style="color:#900;font-weight:bold">c</span>(<span style="color:#099">.80</span>, <span style="color:#099">.85</span>, <span style="color:#099">.90</span>, <span style="color:#099">.95</span>, <span style="color:#099">.95</span>, <span style="color:#099">.96</span>, <span style="color:#099">.97</span>, <span style="color:#099">.98</span>, <span style="color:#099">.99</span>, <span style="color:#099">1</span>), na.rm <span style="color:#000;font-weight:bold">=</span> <span style="color:#000;font-weight:bold">TRUE</span>)
</code></pre></div><pre><code>##  80%  85%  90%  95%  95%  96%  97%  98%  99% 100% 
##    0    0    0    2    2    2    3    4    6   25
</code></pre><p>The output shows that ~90% of students are reporting no in-school suspensions, about 97% of student reported 3 or less suspensions, and the top 1% of students reported at least 6 suspensions. This variable has many rare, high values that will need to be protected.</p>
<p>Although the above output provides sufficient information to determine the rare values of <code>iss_off</code>, I usually always inspect frequency tables unless there are just too many possible values to make sense of. It is often useful to see the frequency of responses for all values, especially if there are not pre-determined thresholds for percentiles to protect against. Here is the frequency table for <code>iss_off</code> (produced with minor edits to be more readable):</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#998;font-style:italic">#frequency table</span>
<span style="color:#900;font-weight:bold">table</span>(sim_df<span style="color:#000;font-weight:bold">$</span>iss_off)
</code></pre></div><table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:right;"> 0 </th>
   <th style="text-align:right;"> 1 </th>
   <th style="text-align:right;"> 2 </th>
   <th style="text-align:right;"> 3 </th>
   <th style="text-align:right;"> 4 </th>
   <th style="text-align:right;"> 5 </th>
   <th style="text-align:right;"> 6 </th>
   <th style="text-align:right;"> 7 </th>
   <th style="text-align:right;"> 8 </th>
   <th style="text-align:right;"> 9 </th>
   <th style="text-align:right;"> 10 </th>
   <th style="text-align:right;"> 11 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 21500 </td>
   <td style="text-align:right;"> 1151 </td>
   <td style="text-align:right;"> 454 </td>
   <td style="text-align:right;"> 225 </td>
   <td style="text-align:right;"> 168 </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 89 </td>
   <td style="text-align:right;"> 49 </td>
   <td style="text-align:right;"> 18 </td>
   <td style="text-align:right;"> 30 </td>
   <td style="text-align:right;"> 16 </td>
   <td style="text-align:right;"> 9 </td>
  </tr>
</tbody>
</table>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:right;"> 12 </th>
   <th style="text-align:right;"> 13 </th>
   <th style="text-align:right;"> 14 </th>
   <th style="text-align:right;"> 15 </th>
   <th style="text-align:right;"> 16 </th>
   <th style="text-align:right;"> 17 </th>
   <th style="text-align:right;"> 18 </th>
   <th style="text-align:right;"> 19 </th>
   <th style="text-align:right;"> 20 </th>
   <th style="text-align:right;"> 21 </th>
   <th style="text-align:right;"> 22 </th>
   <th style="text-align:right;"> 23 </th>
   <th style="text-align:right;"> 24 </th>
   <th style="text-align:right;"> 25 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 14 </td>
   <td style="text-align:right;"> 7 </td>
   <td style="text-align:right;"> 15 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 4 </td>
  </tr>
</tbody>
</table>
<p>Consistent with the percentile calculations, the frequency counts become drastically smaller when the response is 6 in-school suspensions or more. The table also shows that most values over 10 have less than 10 respondents, and values over 19 start to become unique.</p>
<p>We will calculate the same percentiles for our remaining continuous variables since they were all highly skewed. For <code>iss_days</code>:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#998;font-style:italic">#percentiles</span>
<span style="color:#900;font-weight:bold">quantile</span>(sim_df<span style="color:#000;font-weight:bold">$</span>iss_days, <span style="color:#900;font-weight:bold">c</span>(<span style="color:#099">.80</span>, <span style="color:#099">.85</span>, <span style="color:#099">.90</span>, <span style="color:#099">.95</span>, <span style="color:#099">.96</span>, <span style="color:#099">.97</span>, <span style="color:#099">.98</span>, <span style="color:#099">.99</span>, <span style="color:#099">1</span>), na.rm <span style="color:#000;font-weight:bold">=</span> <span style="color:#000;font-weight:bold">TRUE</span>)
</code></pre></div><pre><code>##  80%  85%  90%  95%  96%  97%  98%  99% 100% 
##    0    0    0    2    2    3    4    7   31
</code></pre><p>We can see that, again, ~90% of students reported no days of in-school suspension. The top 1% of students reported at least 7 days in suspension but the max value is 31. We could calculate values at higher percentiles (&gt;99%), but instead we will look at the frequency of all responses again:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#998;font-style:italic">#frequency table</span>
<span style="color:#900;font-weight:bold">table</span>(sim_df<span style="color:#000;font-weight:bold">$</span>iss_days)
</code></pre></div><table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:right;"> 0 </th>
   <th style="text-align:right;"> 1 </th>
   <th style="text-align:right;"> 2 </th>
   <th style="text-align:right;"> 3 </th>
   <th style="text-align:right;"> 4 </th>
   <th style="text-align:right;"> 5 </th>
   <th style="text-align:right;"> 6 </th>
   <th style="text-align:right;"> 7 </th>
   <th style="text-align:right;"> 8 </th>
   <th style="text-align:right;"> 9 </th>
   <th style="text-align:right;"> 10 </th>
   <th style="text-align:right;"> 11 </th>
   <th style="text-align:right;"> 12 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 21500 </td>
   <td style="text-align:right;"> 907 </td>
   <td style="text-align:right;"> 525 </td>
   <td style="text-align:right;"> 357 </td>
   <td style="text-align:right;"> 141 </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 76 </td>
   <td style="text-align:right;"> 75 </td>
   <td style="text-align:right;"> 31 </td>
   <td style="text-align:right;"> 31 </td>
   <td style="text-align:right;"> 30 </td>
   <td style="text-align:right;"> 24 </td>
   <td style="text-align:right;"> 17 </td>
  </tr>
</tbody>
</table>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:right;"> 13 </th>
   <th style="text-align:right;"> 14 </th>
   <th style="text-align:right;"> 15 </th>
   <th style="text-align:right;"> 16 </th>
   <th style="text-align:right;"> 17 </th>
   <th style="text-align:right;"> 18 </th>
   <th style="text-align:right;"> 19 </th>
   <th style="text-align:right;"> 20 </th>
   <th style="text-align:right;"> 21 </th>
   <th style="text-align:right;"> 23 </th>
   <th style="text-align:right;"> 24 </th>
   <th style="text-align:right;"> 27 </th>
   <th style="text-align:right;"> 28 </th>
   <th style="text-align:right;"> 30 </th>
   <th style="text-align:right;"> 31 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 13 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 11 </td>
   <td style="text-align:right;"> 9 </td>
   <td style="text-align:right;"> 7 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
</tbody>
</table>
<p>From the frequency table, it is possible to see more detail about the spread of responses, especially at higher values. Although values over 7 represent only 1% of students, responses seem to start becoming rare (i.e., almost unique) after 13 days in suspension.</p>
<p>The next continuous variable is a count of subjective offenses, <code>subj_off</code>:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#998;font-style:italic">#percentiles</span>
<span style="color:#900;font-weight:bold">quantile</span>(sim_df<span style="color:#000;font-weight:bold">$</span>subj_off, <span style="color:#900;font-weight:bold">c</span>(<span style="color:#099">.80</span>, <span style="color:#099">.85</span>, <span style="color:#099">.90</span>, <span style="color:#099">.95</span>, <span style="color:#099">.96</span>, <span style="color:#099">.97</span>, <span style="color:#099">.98</span>, <span style="color:#099">.99</span>, <span style="color:#099">1</span>), na.rm <span style="color:#000;font-weight:bold">=</span> <span style="color:#000;font-weight:bold">TRUE</span>)
</code></pre></div><pre><code>##  80%  85%  90%  95%  96%  97%  98%  99% 100% 
##    0    1    1    3    3    4    6    9   20
</code></pre><p>Similar to the discipline variables above, the majority of students have zero subjective offenses (~80%). However, there seems to be more spread in responses for this variable. For example, more students reported at least 1 offense and higher counts in general compared to the previous variables. Let&rsquo;s take a look at the frequency table:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#998;font-style:italic">#frequency table of subjective offenses</span>
<span style="color:#900;font-weight:bold">table</span>(sim_df<span style="color:#000;font-weight:bold">$</span>subj_off)
</code></pre></div><table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:right;"> 0 </th>
   <th style="text-align:right;"> 1 </th>
   <th style="text-align:right;"> 2 </th>
   <th style="text-align:right;"> 3 </th>
   <th style="text-align:right;"> 4 </th>
   <th style="text-align:right;"> 5 </th>
   <th style="text-align:right;"> 6 </th>
   <th style="text-align:right;"> 7 </th>
   <th style="text-align:right;"> 8 </th>
   <th style="text-align:right;"> 9 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 20130 </td>
   <td style="text-align:right;"> 1859 </td>
   <td style="text-align:right;"> 641 </td>
   <td style="text-align:right;"> 479 </td>
   <td style="text-align:right;"> 135 </td>
   <td style="text-align:right;"> 136 </td>
   <td style="text-align:right;"> 82 </td>
   <td style="text-align:right;"> 77 </td>
   <td style="text-align:right;"> 63 </td>
   <td style="text-align:right;"> 73 </td>
  </tr>
</tbody>
</table>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:right;"> 10 </th>
   <th style="text-align:right;"> 11 </th>
   <th style="text-align:right;"> 12 </th>
   <th style="text-align:right;"> 13 </th>
   <th style="text-align:right;"> 14 </th>
   <th style="text-align:right;"> 15 </th>
   <th style="text-align:right;"> 16 </th>
   <th style="text-align:right;"> 17 </th>
   <th style="text-align:right;"> 18 </th>
   <th style="text-align:right;"> 19 </th>
   <th style="text-align:right;"> 20 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 60 </td>
   <td style="text-align:right;"> 56 </td>
   <td style="text-align:right;"> 19 </td>
   <td style="text-align:right;"> 21 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 19 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 10 </td>
  </tr>
</tbody>
</table>
<p>Consistent with the percentile calculations, frequencies for values around 9-11+ start decreasing drastically. We can also see that values above 13 start becoming very rare (i.e., almost unique).</p>
<p>The last continuous variable, <code>days_absent</code>, was also highly skewed but it had a much larger range (0-116). Thus, there will be more individuals with rare responses in the tails. Once again, we will first calculate the values corresponding to sample percentiles in the tail of the distribution:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#998;font-style:italic">#percentiles</span>
<span style="color:#900;font-weight:bold">quantile</span>(sim_df<span style="color:#000;font-weight:bold">$</span>days_absent, <span style="color:#900;font-weight:bold">c</span>(<span style="color:#099">.80</span>, <span style="color:#099">.85</span>, <span style="color:#099">.90</span>, <span style="color:#099">.95</span>, <span style="color:#099">.96</span>, <span style="color:#099">.97</span>, <span style="color:#099">.98</span>, <span style="color:#099">.99</span>, <span style="color:#099">1</span>), na.rm <span style="color:#000;font-weight:bold">=</span> <span style="color:#000;font-weight:bold">TRUE</span>) 
</code></pre></div><pre><code>##  80%  85%  90%  95%  96%  97%  98%  99% 100% 
##    4    5    7   11   12   14   18   30  116
</code></pre><p>The percentiles show that much more of the distribution is in the tails for number of days absent, compared to the previous discipline variables. About 80% of students had at least 4 days absent, the top 5% and 1% of students had at least 11 or 30 days absent, respectively. It may be useful to calculate different percentiles for this variable, but as you can probably tell by now, I prefer to look at the full frequency distribution. Thus, I would still calculate a frequency table for <code>days_absent</code> even though there are many values:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#998;font-style:italic">#frequency table</span>
<span style="color:#900;font-weight:bold">table</span>(sim_df<span style="color:#000;font-weight:bold">$</span>days_absent)
</code></pre></div><table class="table" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:right;"> 0 </th>
   <th style="text-align:right;"> 1 </th>
   <th style="text-align:right;"> 2 </th>
   <th style="text-align:right;"> 3 </th>
   <th style="text-align:right;"> 4 </th>
   <th style="text-align:right;"> 5 </th>
   <th style="text-align:right;"> 6 </th>
   <th style="text-align:right;"> 7 </th>
   <th style="text-align:right;"> 8 </th>
   <th style="text-align:right;"> 9 </th>
   <th style="text-align:right;"> 10 </th>
   <th style="text-align:right;"> 11 </th>
   <th style="text-align:right;"> 12 </th>
   <th style="text-align:right;"> 13 </th>
   <th style="text-align:right;"> 14 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 4516 </td>
   <td style="text-align:right;"> 5851 </td>
   <td style="text-align:right;"> 4289 </td>
   <td style="text-align:right;"> 3057 </td>
   <td style="text-align:right;"> 2610 </td>
   <td style="text-align:right;"> 1193 </td>
   <td style="text-align:right;"> 814 </td>
   <td style="text-align:right;"> 612 </td>
   <td style="text-align:right;"> 333 </td>
   <td style="text-align:right;"> 225 </td>
   <td style="text-align:right;"> 196 </td>
   <td style="text-align:right;"> 183 </td>
   <td style="text-align:right;"> 161 </td>
   <td style="text-align:right;"> 142 </td>
   <td style="text-align:right;"> 140 </td>
  </tr>
</tbody>
</table>
<table class="table" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:right;"> 15 </th>
   <th style="text-align:right;"> 16 </th>
   <th style="text-align:right;"> 17 </th>
   <th style="text-align:right;"> 18 </th>
   <th style="text-align:right;"> 19 </th>
   <th style="text-align:right;"> 20 </th>
   <th style="text-align:right;"> 21 </th>
   <th style="text-align:right;"> 22 </th>
   <th style="text-align:right;"> 23 </th>
   <th style="text-align:right;"> 24 </th>
   <th style="text-align:right;"> 25 </th>
   <th style="text-align:right;"> 26 </th>
   <th style="text-align:right;"> 27 </th>
   <th style="text-align:right;"> 28 </th>
   <th style="text-align:right;"> 29 </th>
   <th style="text-align:right;"> 30 </th>
   <th style="text-align:right;"> 31 </th>
   <th style="text-align:right;"> 32 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 94 </td>
   <td style="text-align:right;"> 41 </td>
   <td style="text-align:right;"> 36 </td>
   <td style="text-align:right;"> 38 </td>
   <td style="text-align:right;"> 23 </td>
   <td style="text-align:right;"> 22 </td>
   <td style="text-align:right;"> 27 </td>
   <td style="text-align:right;"> 18 </td>
   <td style="text-align:right;"> 19 </td>
   <td style="text-align:right;"> 26 </td>
   <td style="text-align:right;"> 14 </td>
   <td style="text-align:right;"> 10 </td>
   <td style="text-align:right;"> 17 </td>
   <td style="text-align:right;"> 10 </td>
   <td style="text-align:right;"> 17 </td>
   <td style="text-align:right;"> 17 </td>
   <td style="text-align:right;"> 12 </td>
   <td style="text-align:right;"> 16 </td>
  </tr>
</tbody>
</table>
<table class="table" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:right;"> 33 </th>
   <th style="text-align:right;"> 34 </th>
   <th style="text-align:right;"> 35 </th>
   <th style="text-align:right;"> 36 </th>
   <th style="text-align:right;"> 37 </th>
   <th style="text-align:right;"> 38 </th>
   <th style="text-align:right;"> 39 </th>
   <th style="text-align:right;"> 40 </th>
   <th style="text-align:right;"> 41 </th>
   <th style="text-align:right;"> 42 </th>
   <th style="text-align:right;"> 43 </th>
   <th style="text-align:right;"> 44 </th>
   <th style="text-align:right;"> 45 </th>
   <th style="text-align:right;"> 46 </th>
   <th style="text-align:right;"> 47 </th>
   <th style="text-align:right;"> 48 </th>
   <th style="text-align:right;"> 49 </th>
   <th style="text-align:right;"> 50 </th>
   <th style="text-align:right;"> 51 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 12 </td>
   <td style="text-align:right;"> 20 </td>
   <td style="text-align:right;"> 21 </td>
   <td style="text-align:right;"> 10 </td>
   <td style="text-align:right;"> 24 </td>
   <td style="text-align:right;"> 11 </td>
   <td style="text-align:right;"> 7 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 9 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 7 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
</tbody>
</table>
<table class="table" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:right;"> 52 </th>
   <th style="text-align:right;"> 53 </th>
   <th style="text-align:right;"> 54 </th>
   <th style="text-align:right;"> 55 </th>
   <th style="text-align:right;"> 56 </th>
   <th style="text-align:right;"> 57 </th>
   <th style="text-align:right;"> 58 </th>
   <th style="text-align:right;"> 59 </th>
   <th style="text-align:right;"> 60 </th>
   <th style="text-align:right;"> 63 </th>
   <th style="text-align:right;"> 69 </th>
   <th style="text-align:right;"> 75 </th>
   <th style="text-align:right;"> 79 </th>
   <th style="text-align:right;"> 83 </th>
   <th style="text-align:right;"> 95 </th>
   <th style="text-align:right;"> 101 </th>
   <th style="text-align:right;"> 111 </th>
   <th style="text-align:right;"> 116 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 7 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
</tbody>
</table>
<p>From the frequency table, we can see that the cell sizes for values 0-14 are actually pretty high and in the triple digits. Values after 14 start becoming increasingly small and potentially risky, whereas values past 38 days have counts in the single digits and could be considered rare responses (depending on your threshold). There are also many unique values in the extreme tail of the distribution (starting at 51 days) that will lead to high re-identification risk.</p>
<p>Although exploring the distributions of continuous variables does not give you a definitive re-identification risk value, it does provide information about the amount of risky responses present in that variable. In later sections we will use this information to determine how much protection to apply for these continuous variables. Ultimately, we will want to assess the risk of our continuous (and categorical) variables after we apply statistical disclosure control methods to make sure we are protecting the risky response appropriately. The next section will go through the statistical disclosure control process.</p>




<h1 id="statistical-disclosure-control-methods">Statistical Disclosure Control Methods
  <a href="#statistical-disclosure-control-methods"></a>
</h1>
<p>Statistical disclosure control (SDC) is a process meant to de-identify data so that is can be archived or released. The aim is to find a balance between maximizing privacy protection and minimizing information loss so that the data is protected but still useful for analysis. SDC methods are used to achieve an appropriate level of disclosure risk by altering the data in various ways. Perturbative methods alter the values of continuous variables so that the &ldquo;true&rdquo; responses of individuals cannot be known but the statistical properties of the variable remain intact. These methods include adding statistical noise, Post-Randomization Method (PRAM), micro-aggregation, and shuffling. Non-perturbative methods reduce the level of detail among variables without altering the original values, such as global recoding, top/bottom coding continuous variables, and local suppression. Generating synthetic data that maintains the statistical properties and relations of the original data is also an acceptable SDC method. Both perturbative and non-perturbative methods can be implemented in <code>{sdcMicro}</code>, however, synthetic data generation requires other R packages (e.g., 
<a href="https://www.jstatsoft.org/article/view/v079i10" target="_blank" rel="noopener">simPop</a>) or software.</p>
<p>For this blog, we will be using non-perturbative SDC methods to reduce the amount of disclosure risk to an acceptable level in our data. Similar to assessing disclosure risk, different SDC methods are often used for continuous vs. categorical variables. As mentioned in previous sections, the desired level of disclosure risk is a complicated decision that should be decided by the data custodian, data providers, and based on any relevant legislative regulations. In our case, we will apply SDC methods to top/bottom code at least the top/bottom 0.1% of students while also protecting cell sizes smaller than 10 for continuous variables. For categorical variables, we will use SDC methods to achieve 5-anonymity - assuming student data will be shared with researchers under a data sharing agreement but without a FERPA exception (i.e., fully de-identified).</p>




<h2 id="recode-continuous-variables">Recode Continuous Variables
  <a href="#recode-continuous-variables"><svg class="anchor-symbol" aria-hidden="true" height="26" width="26" viewBox="0 0 22 22" xmlns="http://www.w3.org/2000/svg">
      <path d="M0 0h24v24H0z" fill="currentColor"></path>
      <path d="M3.9 12c0-1.71 1.39-3.1 3.1-3.1h4V7H7c-2.76.0-5 2.24-5 5s2.24 5 5 5h4v-1.9H7c-1.71.0-3.1-1.39-3.1-3.1zM8 13h8v-2H8v2zm9-6h-4v1.9h4c1.71.0 3.1 1.39 3.1 3.1s-1.39 3.1-3.1 3.1h-4V17h4c2.76.0 5-2.24 5-5s-2.24-5-5-5z"></path>
    </svg></a>
</h2>
<p>Top and/or bottom coding can be applied to continuous variables to protect the rare values in the tails of distributions. Values above or below a certain threshold are grouped together and recoded (e.g., ages 18+). Top/bottom coding is most useful when there are only a few individuals in the tails of the distribution or when direct linking is not a disclosure risk concern but you still want to protect rare responses. As always, deciding upon a threshold can be challenging and should take into account the distribution of the variable, disclosure scenarios, as well as the intended use of the variable (i.e., balance data utility).</p>
<p>The first continuous variable, <code>gpa</code>, could be recoded into categorical intervals (e.g., 1-2; 3.67-4) or top/bottom coded. We will do the latter. Based on the risk assessment and thresholds specified above, we only need to bottom code <code>gpa</code> for values less than or equal to 1.33 (i.e., bottom 0.1%), however, we will bottom code values less than 2 to create more equal frequencies in the tails and add a little more protection for those with lower GPAs.</p>
<p>Top and bottom coding can be completed in <code>{sdcMicro}</code> with the <code>topBotCoding()</code> function. We will use our <code>initial_sdcobj</code> sdcMicro object that we created above when assessing risk and will need to save the output to a new object that includes our bottom coded values (<code>tbcode_sdcobj</code>). We also need to to specify the <code>value</code> to top or bottom code (e.g., 2 = bottom codes values <em>less than</em> 2), as well as the <code>replacement</code> value that will be substituted for values above/below your threshold. The <code>replacement</code> value has to be an integer for initial recoding, but can be transformed to other complex values (e.g., <code>&lt;2</code>) or factors/characters (e.g., <code>less than 2</code>) afterwards. Let&rsquo;s look at an example in which we are bottom coding <code>gpa</code> for values under 2 and replacing all values &lt;2 with 1:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#998;font-style:italic">#bottom code gpa</span>
tbcode_sdcobj <span style="color:#000;font-weight:bold">&lt;-</span> <span style="color:#900;font-weight:bold">topBotCoding</span>(obj <span style="color:#000;font-weight:bold">=</span> initial_sdcobj, <span style="color:#998;font-style:italic">#object you created above when top coding</span>
                              column <span style="color:#000;font-weight:bold">=</span> <span style="color:#d14">&#34;gpa&#34;</span>, <span style="color:#998;font-style:italic">#variable to top/bottom code</span>
                              value <span style="color:#000;font-weight:bold">=</span> <span style="color:#099">2</span>, <span style="color:#998;font-style:italic">#number that will be bottom coded (&lt;2 will be recoded)</span>
                              replacement <span style="color:#000;font-weight:bold">=</span> <span style="color:#099">1</span>, <span style="color:#998;font-style:italic">#integer that will replace bottom coded values</span>
                              kind <span style="color:#000;font-weight:bold">=</span> <span style="color:#d14">&#34;bottom&#34;</span>) <span style="color:#998;font-style:italic">#specify top or bottom coding</span>
</code></pre></div><p><em>Note</em>: It is important to always be mindful of the <code>replacement</code> value you choose and the sequence in which you complete top and bottom coding for a single variable. For example, if you bottom code values under a certain threshold (e.g., 2.33) and specify a large <code>replacement</code> value (e.g., 233), it is likely that those bottom coded values (now all 233) will also be recoded when top-coding (e.g., values &gt; 3 now includes 233). Top coding values above 3 will now include 233 (all bottom coded values). It is necessary to select a smaller <code>replacement</code> value or complete top coding first to prevent this.</p>
<p>By running the code above, we are bottom coding <code>gpa</code> (from our initial <code>sdcMicro</code> object) for values under 2.33, recoding those values as 2s, and saving the variable in a new <code>sdcMicro</code> object. Every time a transformation is made to variables in the data set, the resulting modified data set is stored within the <code>sdcMicro</code> object (i.e., manipulated data) along with the raw data set (i.e., original data). At any point during the de-identification process, you can extract your manipulated data with <code>extractManipData()</code> or access it within the <code>sdcMicro</code> object (<code>tbcode_sdcobj@manipNumVars$gpa</code>). For example, to compare the frequency tables of our raw data with the newly bottom coded values for <code>gpa</code>:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#998;font-style:italic">#Raw data</span>
<span style="color:#900;font-weight:bold">table</span>(sim_df<span style="color:#000;font-weight:bold">$</span>gpa)
</code></pre></div><table class="table" style="width: auto !important; ">
 <thead>
  <tr>
   <th style="text-align:right;"> 1 </th>
   <th style="text-align:right;"> 1.33 </th>
   <th style="text-align:right;"> 1.67 </th>
   <th style="text-align:right;"> 2 </th>
   <th style="text-align:right;"> 2.33 </th>
   <th style="text-align:right;"> 2.67 </th>
   <th style="text-align:right;"> 3 </th>
   <th style="text-align:right;"> 3.33 </th>
   <th style="text-align:right;"> 3.67 </th>
   <th style="text-align:right;"> 4 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 37 </td>
   <td style="text-align:right;"> 283 </td>
   <td style="text-align:right;"> 2011 </td>
   <td style="text-align:right;"> 4037 </td>
   <td style="text-align:right;"> 6281 </td>
   <td style="text-align:right;"> 7779 </td>
   <td style="text-align:right;"> 3123 </td>
   <td style="text-align:right;"> 1139 </td>
   <td style="text-align:right;"> 305 </td>
  </tr>
</tbody>
</table>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#998;font-style:italic">#Manipulated data</span>
<span style="color:#900;font-weight:bold">table</span>(tbcode_sdcobj<span style="color:#000;font-weight:bold">@</span>manipNumVars<span style="color:#000;font-weight:bold">$</span>gpa)
</code></pre></div><table class="table" style="width: auto !important; ">
 <thead>
  <tr>
   <th style="text-align:right;"> 1 </th>
   <th style="text-align:right;"> 2 </th>
   <th style="text-align:right;"> 2.33 </th>
   <th style="text-align:right;"> 2.67 </th>
   <th style="text-align:right;"> 3 </th>
   <th style="text-align:right;"> 3.33 </th>
   <th style="text-align:right;"> 3.67 </th>
   <th style="text-align:right;"> 4 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 325 </td>
   <td style="text-align:right;"> 2011 </td>
   <td style="text-align:right;"> 4037 </td>
   <td style="text-align:right;"> 6281 </td>
   <td style="text-align:right;"> 7779 </td>
   <td style="text-align:right;"> 3123 </td>
   <td style="text-align:right;"> 1139 </td>
   <td style="text-align:right;"> 305 </td>
  </tr>
</tbody>
</table>
<p>This step can be done as a manual check to make sure the top/bottom coding is operating as expected.</p>
<p>Since the discipline and attendance variables had such a high, positive skew, we only need to top code values above our threshold (i.e., top 1% while protecting cell sizes under 10). We can compute the value that makes up the top 1% of students with the same <code>quantile()</code> function from the risk assessment. For <code>iss_off</code>:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#998;font-style:italic">#in school suspensions top 0.1%</span>
<span style="color:#900;font-weight:bold">quantile</span>(sim_df<span style="color:#000;font-weight:bold">$</span>iss_off, <span style="color:#900;font-weight:bold">c</span>(<span style="color:#099">.999</span>), na.rm <span style="color:#000;font-weight:bold">=</span> <span style="color:#000;font-weight:bold">TRUE</span>)
</code></pre></div><pre><code>## 99.9% 
##    18
</code></pre><p>Although the top 0.1% of students correspond to values of 18 and higher, the frequency tables from the risk assessment show that values above 10 need to be protected since the frequency count for the value of 11 is below our cell size threshold of 10. Therefore, we will top code <code>iss_off</code> for values higher than 10 and replace it with 11. It is important to note that the first time we used top/bottom coding we used our initial <code>sdcMicro</code> object (<code>initial_sdcobj</code>), however, from here on we will want to use the most recent object that contains our transformed values. For example, when top coding <code>iss_off</code>, we will use the <code>tbcode_sdcobj</code> object to make further changes. Since we are still top/bottom coding, I will also save it to the same object (<code>tbcode_sdcobj</code>):</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#998;font-style:italic">#top code iss_off</span>
tbcode_sdcobj <span style="color:#000;font-weight:bold">&lt;-</span> <span style="color:#900;font-weight:bold">topBotCoding</span>(obj <span style="color:#000;font-weight:bold">=</span> tbcode_sdcobj, <span style="color:#998;font-style:italic">#object created above when top/bottom coding gpa</span>
                              column <span style="color:#000;font-weight:bold">=</span> <span style="color:#d14">&#34;iss_off&#34;</span>,
                              value <span style="color:#000;font-weight:bold">=</span> <span style="color:#099">10</span>, <span style="color:#998;font-style:italic">#values 11+ are top coded</span>
                              replacement <span style="color:#000;font-weight:bold">=</span> <span style="color:#099">11</span>,
                              kind <span style="color:#000;font-weight:bold">=</span> <span style="color:#d14">&#34;top&#34;</span>)
</code></pre></div><p>This amount of top coding may be too much since we are taking away a lot of the variability in the tails of the distribution. If a main priority of the data is to answer questions about the amount of in school suspensions, especially at higher levels, you may want to consider changing the threshold for this variable or possibly considering a different type of release of adding more restrictions to protect privacy into a data sharing agreement. This is also the reason why it is so important to assess data utility after applying methods to de-identify data.</p>
<p>We can repeat these steps for the other three continuous variables. For <code>iss_days</code> we will top code values above 13, and for <code>subj_off</code> and <code>days_absent</code> we will top code values above 13 and 38 respectively:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">tbcode_sdcobj <span style="color:#000;font-weight:bold">&lt;-</span> <span style="color:#900;font-weight:bold">topBotCoding</span>(obj <span style="color:#000;font-weight:bold">=</span> tbcode_sdcobj, <span style="color:#998;font-style:italic">#same top/bottom code object</span>
                              column <span style="color:#000;font-weight:bold">=</span> <span style="color:#d14">&#34;iss_days&#34;</span>,
                              value <span style="color:#000;font-weight:bold">=</span> <span style="color:#099">13</span>, 
                              replacement <span style="color:#000;font-weight:bold">=</span> <span style="color:#099">14</span>,
                              kind <span style="color:#000;font-weight:bold">=</span> <span style="color:#d14">&#34;top&#34;</span>)

tbcode_sdcobj <span style="color:#000;font-weight:bold">&lt;-</span> <span style="color:#900;font-weight:bold">topBotCoding</span>(obj <span style="color:#000;font-weight:bold">=</span> tbcode_sdcobj,
                              column <span style="color:#000;font-weight:bold">=</span> <span style="color:#d14">&#34;subj_off&#34;</span>,
                              value <span style="color:#000;font-weight:bold">=</span> <span style="color:#099">13</span>, 
                              replacement <span style="color:#000;font-weight:bold">=</span> <span style="color:#099">14</span>,
                              kind <span style="color:#000;font-weight:bold">=</span> <span style="color:#d14">&#34;top&#34;</span>)

tbcode_sdcobj <span style="color:#000;font-weight:bold">&lt;-</span> <span style="color:#900;font-weight:bold">topBotCoding</span>(obj <span style="color:#000;font-weight:bold">=</span> tbcode_sdcobj, 
                              column <span style="color:#000;font-weight:bold">=</span> <span style="color:#d14">&#34;days_absent&#34;</span>,
                              value <span style="color:#000;font-weight:bold">=</span> <span style="color:#099">38</span>, 
                              replacement <span style="color:#000;font-weight:bold">=</span> <span style="color:#099">39</span>,
                              kind <span style="color:#000;font-weight:bold">=</span> <span style="color:#d14">&#34;top&#34;</span>)
</code></pre></div>



<h2 id="initial-local-suppression-for-categorical-variables">Initial Local Suppression for Categorical Variables
  <a href="#initial-local-suppression-for-categorical-variables"><svg class="anchor-symbol" aria-hidden="true" height="26" width="26" viewBox="0 0 22 22" xmlns="http://www.w3.org/2000/svg">
      <path d="M0 0h24v24H0z" fill="currentColor"></path>
      <path d="M3.9 12c0-1.71 1.39-3.1 3.1-3.1h4V7H7c-2.76.0-5 2.24-5 5s2.24 5 5 5h4v-1.9H7c-1.71.0-3.1-1.39-3.1-3.1zM8 13h8v-2H8v2zm9-6h-4v1.9h4c1.71.0 3.1 1.39 3.1 3.1s-1.39 3.1-3.1 3.1h-4V17h4c2.76.0 5-2.24 5-5s-2.24-5-5-5z"></path>
    </svg></a>
</h2>
<p>To de-identify categorical variables, we will be using the <em>k</em>-anonymity privacy model with a <em>k</em> = 5. To achieve 5-anonymity, a balance of generalization and cell suppression can be used. Generalization refers to recoding or aggregating categorical variables, whereas cell suppression involves transforming certain values to missing. Traditional SDC methods have used record suppression (i.e., removing risky rows from the data set) for de-identification, however, this disproportionately affects minority subgroups and can drastically decrease data utility. One of the advantages of using <code>{sdcMicro}</code> for non-perturbative SDC methods, is the ability to implement cell suppression (called local suppression in <code>{sdcMicro}</code>) in which an algorithm is used to identify the optimal value/responses to suppress to achieve <em>k</em>-anonymity instead of suppressing all rows that do not meet <em>k</em>-anonymity.</p>
<p>In practice, categorical variables are usually recoded before applying local suppression to reduce the amount of suppression needed. However, I find it helpful to first review the amount of cell suppression necessary to achieve <em>k</em>-anonymity with the raw variables before recoding. This will provide information on which variables are leading to high re-identification risk (e.g., variables with high cell suppression) and how much recoding should be completed.</p>
<p>The <code>kAnon()</code> function in <code>{sdcMicro}</code> can be used to apply local suppression to achieve <em>k</em>-anonymity. Within this function, we can specify an <code>importance</code> vector which corresponds to the categorical variables in our data. This <code>importance</code> ranking specifies the amount of local suppression to do for each variable. For example, if the <code>importance</code> vector is <code>c(1, 2, 3)</code>, the first variable is the most important and will have the least cell suppression, whereas the last variable is least important and will most likely have the most cell suppression. This decision should be based off of which variables are most important to retain as raw as possible for analysis. If you do not specify an <code>importance</code> vector, the default is to make variables with more response options less important and thus have more cell suppression.</p>
<p>To view the amount of cell suppression needed to achieve 5-anonymity, we will use <code>kAnon()</code> on our initial <code>{sdcMicro}</code> object (<code>initial_sdcobj</code>) and save it as a new object indicating it was suppressed (<code>sdcobj_sup</code>).</p>
<p><strong>Warning:</strong> depending on the sample size and amount of categorical variables, this function can be very computationally intensive - leading to long run times. It can be helpful to first run on a subset of the data before applying on the full sample to make sure you have enough computational power.</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">sdcobj_sup <span style="color:#000;font-weight:bold">&lt;-</span> <span style="color:#900;font-weight:bold">kAnon</span>(initial_sdcobj, <span style="color:#998;font-style:italic">#initial object</span>
                    importance<span style="color:#000;font-weight:bold">=</span><span style="color:#900;font-weight:bold">c</span>(<span style="color:#099">1</span>, <span style="color:#099">3</span>, <span style="color:#099">2</span>, <span style="color:#099">4</span>, <span style="color:#099">5</span>, <span style="color:#099">6</span>, <span style="color:#099">7</span>), <span style="color:#998;font-style:italic">#importance ranking for categorical variables</span>
                    k <span style="color:#000;font-weight:bold">=</span> <span style="color:#900;font-weight:bold">c</span>(<span style="color:#099">5</span>)) <span style="color:#998;font-style:italic">#k-anonymity value</span>
</code></pre></div><p>The results of the local suppression are saved within our new <code>{sdcMicro}</code> object. To view the amount of suppression necessary to achieve 5-anonymity with our raw categorical variables, we just need to view our new object. This will give you a lot of information, but for now we will just focus on the amount of suppression applied.</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">sdcobj_sup
</code></pre></div><pre><code>## Local suppression:
</code></pre><pre><code>##       KeyVar | Suppressions (#) | Suppressions (%)
##  grade_level |                2 |            0.008
##          sex |               15 |            0.060
##         race |               43 |            0.172
##     econ_dis |              115 |            0.460
##   disability |               82 |            0.328
##      dis_cat |             1252 |            5.008
##         lang |             2191 |            8.764
</code></pre><pre><code>## ----------------------------------------------------------------------
</code></pre><p>The above output presents the amount of cell suppression required per variable to achieve 5-anonymity based on our importance vector. For example, since we stated <code>grade_level</code> was the most important variable, it only has two responses that were suppressed (i.e., changed to missing). Alternatively, language has the most cell suppression (8.7% of responses) because it was specified as least important and it has the most response choices (9 options).</p>
<p>Technically, you could export the manipulated data after this step and it could be considered de-identified (after re-assessing risk) since we top/bottom coded our continuous variables and achieved 5-anonymity with local suppression for categorical variables. However, we can reduce the amount of suppression needed to achieve <em>k</em>-anonymity and likely increase data utility by recoding our categorical variables before we apply local suppression.</p>
<p>These initial suppression results suggest that we can reduce the amount of suppression applied by recoding <code>lang</code> and <code>dis_cat</code> since those variables lead to the most cell suppression. It also makes intuitive sense to generalize those variables since they both have many response options.</p>




<h2 id="recode-categorical-variables">Recode Categorical Variables
  <a href="#recode-categorical-variables"><svg class="anchor-symbol" aria-hidden="true" height="26" width="26" viewBox="0 0 22 22" xmlns="http://www.w3.org/2000/svg">
      <path d="M0 0h24v24H0z" fill="currentColor"></path>
      <path d="M3.9 12c0-1.71 1.39-3.1 3.1-3.1h4V7H7c-2.76.0-5 2.24-5 5s2.24 5 5 5h4v-1.9H7c-1.71.0-3.1-1.39-3.1-3.1zM8 13h8v-2H8v2zm9-6h-4v1.9h4c1.71.0 3.1 1.39 3.1 3.1s-1.39 3.1-3.1 3.1h-4V17h4c2.76.0 5-2.24 5-5s-2.24-5-5-5z"></path>
    </svg></a>
</h2>
<p>Global recoding, also called generalization or aggregation, combines multiple response options of a single variable into a single, new category. For example, grade level could be aggregated from its original values (e.g., 1st, 6th grade) to higher levels (e.g., Elementary, Middle) to reduce re-identification risk. Based on the importance of our variables and the initial suppression results, we will aggregate language (<code>lang</code>) and disability categories (<code>dis_cat</code>) to reduce our cell suppression. Deciding on how to aggregate variables can be very difficult and sometimes impossible while maintaining data utility (e.g., original dichotomous variables). Subject matter experts should be consulted when decided how to group variable response options.</p>
<p>In addition to consulting with subject matter experts, it can be helpful to look at frequency tables of responses per variable. Instead of using <code>table()</code>, we will use <code>summary()</code> so that we can get an ordered frequency table with the <code>fct_infreq</code> function:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#998;font-style:italic">#ordered frequency table</span>
<span style="color:#900;font-weight:bold">summary</span>(<span style="color:#900;font-weight:bold">fct_infreq</span>(sim_df<span style="color:#000;font-weight:bold">$</span>lang))
</code></pre></div><pre><code>##    English    Spanish      Other    Chinese Vietnamese     Arabic    Russian 
##      18786       3173       2392        287        117         96         69 
##     German    Swahili 
##         64         16
</code></pre><p>Based on these frequencies, we decide to leave <code>English</code> and <code>Spanish</code> as single responses because those cell sizes are adequate. Since there is already an option for <code>Other</code> and the cell sizes for the other languages are much smaller, we will recode all other languages as <code>Other</code> - assuming analysts don&rsquo;t need this level of detail. This can be implemented with the <code>groupAndRename</code> function in <code>{sdcMicro}</code>. It is important to make sure to use the <code>{sdcMicro}</code> object we applied top/bottom coding to (<code>tbcode_sdcobj</code>) to apply the recoding to that same manipulated data set. We will save the results to a new object indicated it has been recoded (<code>sdcobj_recode</code>):</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">sdcobj_recode <span style="color:#000;font-weight:bold">&lt;-</span> <span style="color:#900;font-weight:bold">groupAndRename</span>(obj <span style="color:#000;font-weight:bold">=</span> tbcode_sdcobj, <span style="color:#998;font-style:italic">#use working object</span>
                                    var <span style="color:#000;font-weight:bold">=</span> <span style="color:#d14">&#34;lang&#34;</span>, <span style="color:#998;font-style:italic">#variable to recode</span>
                                    before <span style="color:#000;font-weight:bold">=</span> <span style="color:#900;font-weight:bold">c</span>(<span style="color:#d14">&#34;Other&#34;</span>,<span style="color:#d14">&#34;Chinese&#34;</span>, <span style="color:#d14">&#34;Vietnamese&#34;</span>, 
                                               <span style="color:#d14">&#34;Arabic&#34;</span>, <span style="color:#d14">&#34;Russian&#34;</span>, <span style="color:#d14">&#34;German&#34;</span>, <span style="color:#d14">&#34;Swahili&#34;</span>), <span style="color:#998;font-style:italic">#vector of responses to group</span>
                                    after <span style="color:#000;font-weight:bold">=</span> <span style="color:#900;font-weight:bold">c</span>(<span style="color:#d14">&#34;Other&#34;</span>)) <span style="color:#998;font-style:italic">#name the new group</span>
</code></pre></div><p>Similar to how we checked our recoding for continuous variables, you can check a frequency table of the manipulated variable to manually check the recoding operated as expected:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#900;font-weight:bold">table</span>(sdcobj_recode<span style="color:#000;font-weight:bold">@</span>manipKeyVars<span style="color:#000;font-weight:bold">$</span>lang)
</code></pre></div><pre><code>## 
##   Other English Spanish 
##    3041   18786    3173
</code></pre><p>Everything looks good!</p>
<p>Now, let&rsquo;s take a look at the frequencies for <code>dis_cat</code>:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#900;font-weight:bold">summary</span>(<span style="color:#900;font-weight:bold">fct_infreq</span>(sim_df<span style="color:#000;font-weight:bold">$</span>dis_cat))
</code></pre></div><pre><code>##               Not Applicable Specific Learning Disability 
##                        21235                         1283 
##  Speech/Language Impairments                        Other 
##                          724                          642 
##                       Autism          Developmental Delay 
##                          425                          276 
##      Intellectual Disability        Emotional Disturbance 
##                          231                          184
</code></pre><p>Although these cell sizes are pretty sparse and this variable lead to quite a bit of cell suppression to achieve 5-anonymity, it doesn&rsquo;t make conceptual sense to group many of these disability categories. If this variable was not central for data analysis, it may be best to exclude this variable from the request especially since there is a dichotomous disability variable. This would allow better data utility for the variables that are most important to answer the research questions. Assuming this variable is important for analysis, there are different ways to group the disability categories. You could group the ones with the smallest cell sizes and name the new category all options (e.g., <code>Autism</code> and <code>Emotional Disturbance</code>) or group the options that do make conceptual sense to group and then accept the level of suppression necessary to fully de-identify the data.</p>
<p>We will group <code>Developmental Delay</code> and <code>Intellectual Disability</code> given those are sometimes combined in analyses, but will leave the other responses as is. Another option is to combine <code>Emotional Disturbance</code> with <code>Other</code> since it has a small frequency, however, we will assume it is important to keep this separate even if it will lead to more cell suppression. We can use the same function as above to recode <code>dis_cat</code>:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">sdcobj_recode <span style="color:#000;font-weight:bold">&lt;-</span> <span style="color:#900;font-weight:bold">groupAndRename</span>(obj <span style="color:#000;font-weight:bold">=</span> sdcobj_recode, <span style="color:#998;font-style:italic">#use sdcobj_recode object you made above</span>
                                    var <span style="color:#000;font-weight:bold">=</span> <span style="color:#d14">&#34;dis_cat&#34;</span>,
                                    before <span style="color:#000;font-weight:bold">=</span> <span style="color:#900;font-weight:bold">c</span>(<span style="color:#d14">&#34;Developmental Delay&#34;</span>,<span style="color:#d14">&#34;Intellectual Disability&#34;</span>),
                                    after <span style="color:#000;font-weight:bold">=</span> <span style="color:#900;font-weight:bold">c</span>(<span style="color:#d14">&#34;Developmental Delay/Intellectual Disability&#34;</span>)) 
</code></pre></div>



<h2 id="local-suppression-for-k-anonymity">Local suppression for k-anonymity
  <a href="#local-suppression-for-k-anonymity"><svg class="anchor-symbol" aria-hidden="true" height="26" width="26" viewBox="0 0 22 22" xmlns="http://www.w3.org/2000/svg">
      <path d="M0 0h24v24H0z" fill="currentColor"></path>
      <path d="M3.9 12c0-1.71 1.39-3.1 3.1-3.1h4V7H7c-2.76.0-5 2.24-5 5s2.24 5 5 5h4v-1.9H7c-1.71.0-3.1-1.39-3.1-3.1zM8 13h8v-2H8v2zm9-6h-4v1.9h4c1.71.0 3.1 1.39 3.1 3.1s-1.39 3.1-3.1 3.1h-4V17h4c2.76.0 5-2.24 5-5s-2.24-5-5-5z"></path>
    </svg></a>
</h2>
<p>Now that we have recoded our categorical variables, we can re-run the <code>kAnon()</code> function to see if our recoding reduced the amount of suppression necessary to achieve 5-anonymity. It is important to run this function on the object we saved the recoding to (<code>sdcobj_recode</code>):</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">sdcobj_final <span style="color:#000;font-weight:bold">&lt;-</span> <span style="color:#900;font-weight:bold">kAnon</span>(sdcobj_recode, <span style="color:#998;font-style:italic">#object we have been recoding</span>
                      importance<span style="color:#000;font-weight:bold">=</span><span style="color:#900;font-weight:bold">c</span>(<span style="color:#099">1</span>, <span style="color:#099">3</span>, <span style="color:#099">2</span>, <span style="color:#099">4</span>, <span style="color:#099">5</span>, <span style="color:#099">6</span>, <span style="color:#099">7</span>), 
                      k <span style="color:#000;font-weight:bold">=</span> <span style="color:#900;font-weight:bold">c</span>(<span style="color:#099">5</span>))

sdcobj_final
</code></pre></div><pre><code>## The input dataset consists of 25000 rows and 13 variables.
##   --&gt; Categorical key variables: grade_level, sex, race, econ_dis, disability, dis_cat, lang
##   --&gt; Numerical key variables: gpa, iss_off, iss_days, subj_off, days_absent
## ----------------------------------------------------------------------
</code></pre><pre><code>## Information on categorical key variables:
## 
## Reported is the number, mean size and size of the smallest category &gt;0 for recoded variables.
## In parenthesis, the same statistics are shown for the unmodified data.
## Note: NA (missings) are counted as seperate categories!
</code></pre><pre><code>## ----------------------------------------------------------------------
</code></pre><pre><code>## Infos on 2/3-Anonymity:
## 
## Number of observations violating
##   - 2-anonymity: 0 (0.000%) | in original data: 1257 (5.028%)
##   - 3-anonymity: 0 (0.000%) | in original data: 2177 (8.708%)
##   - 5-anonymity: 0 (0.000%) | in original data: 3313 (13.252%)
## 
## ----------------------------------------------------------------------
</code></pre><pre><code>## Numerical key variables: gpa, iss_off, iss_days, subj_off, days_absent
## 
## Disclosure risk (~100.00% in original data):
##   modified data: [0.00%; 99.80%]
## 
## Current Information Loss in modified data (0.00% in original data):
##   IL1: 18627.40
##   Difference of Eigenvalues: 31.870%
## ----------------------------------------------------------------------
</code></pre><pre><code>## Local suppression:
</code></pre><pre><code>## ----------------------------------------------------------------------
</code></pre><pre><code>## Local suppression:
</code></pre><pre><code>##       KeyVar | Suppressions (#) | Suppressions (%)
##  grade_level |                2 |            0.008
##          sex |               14 |            0.056
##         race |               42 |            0.168
##     econ_dis |              117 |            0.468
##   disability |               69 |            0.276
##      dis_cat |             1127 |            4.508
##         lang |             1636 |            6.544
</code></pre><pre><code>## ----------------------------------------------------------------------
</code></pre><p>Unfortunately, our recoding did not seem to drastically reduce the amount of cell suppression. This is likely because we left a lot of detail in the <code>dis_cat</code> variable. However, it did reduce it a little bit (~2% less suppression for <code>lang</code>). At this point, you should decide whether you want to try additional recoding (or other SDC methods) to further reduce the amount of suppression applied or if this is an acceptable amount of suppression. We will assume this is an acceptable amount of suppression.</p>
<p>Finally, we have top/bottom coded our continuous variables, recoded and applied local suppression to our categorical variables, and saved all of those transformations in our final object: <code>sdcobj_final</code>. In theory, we now have a de-identified data set (based on our thresholds) that we can extract from our <code>{sdcMicro}</code> object with the <code>extractManipData()</code> function:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">anon_df <span style="color:#000;font-weight:bold">&lt;-</span> <span style="color:#900;font-weight:bold">extractManipData</span>(sdcobj_final)
</code></pre></div><p>However, it is best practice to make sure that the data is adequately de-identified (i.e., re-assess re-identification risk with transformed data) and still useful for analysis before the SDC process is considered complete.</p>




<h1 id="re-assessing-risk">Re-assessing Risk
  <a href="#re-assessing-risk"></a>
</h1>
<p>Once an acceptable amount of SDC is applied, it is best to re-assess re-identification risk to see how much the SDC methods reduced re-identification risk and make sure the data is fully de-identified based on our thresholds.</p>
<p>One important assumption of our <em>k</em>-anonymity privacy model is that missing values (<code>NA</code>) are treated as if they were any other value, as mentioned in the disclosure risk section. If a variable already has missing values, this is most likely not an issue because an intruder cannot know which values are truly missing vs. those that were suppressed for SDC. If a variable does not have missing values before de-identification, then rules around how to deal with small cell suppression for that variable should be created to protect against backward engineering that value. It is possible to infer a student&rsquo;s sex if you know that value was suppressed in an equivalence class of <em>k</em> = 5. For example, if there are four responses for [10th Grade, Male, White&hellip;] and one [10th Grade, NA, White] that was suppressed when applying SDC methods, it is obvious that this <code>NA</code> value is supposed to be Female - making this individual more identifiable. In our case, there was only 2 cell suppression for <code>grade_level</code> which did not have any missing values in our original data. Thus, it may be possible to infer these these 2 values based on the other responses in that equivalence class. If this a reasonable assumption, it may be worth excluding those 2 rows in the de-identified data set or modifying the SDC process to try to reduce these cell suppressions (e.g., more recoding, different importance vectors).</p>
<p>Aside from checking our disclosure risk assumptions, we can re-assess and compare re-identification risk of the de-identified data with the original data set with the same risk assessment methods we used above.</p>




<h3 id="categorical-variables">Categorical Variables
  <a href="#categorical-variables"><svg class="anchor-symbol" aria-hidden="true" height="26" width="26" viewBox="0 0 22 22" xmlns="http://www.w3.org/2000/svg">
      <path d="M0 0h24v24H0z" fill="currentColor"></path>
      <path d="M3.9 12c0-1.71 1.39-3.1 3.1-3.1h4V7H7c-2.76.0-5 2.24-5 5s2.24 5 5 5h4v-1.9H7c-1.71.0-3.1-1.39-3.1-3.1zM8 13h8v-2H8v2zm9-6h-4v1.9h4c1.71.0 3.1 1.39 3.1 3.1s-1.39 3.1-3.1 3.1h-4V17h4c2.76.0 5-2.24 5-5s-2.24-5-5-5z"></path>
    </svg></a>
</h3>
<p>For categorical variables, we can confirm that 5-anonymity has been achieved by re-calculating the number of observations violating <em>k</em>-anonymity. This can be done using the final <code>{sdcMicro}</code> object that contains our de-identified, or manipulated, data set. If our local suppression worked as expected, we should not have any observations violating 5-anonymity:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#900;font-weight:bold">print</span>(sdcobj_final)
</code></pre></div><pre><code>## Infos on 2/3-Anonymity:
## 
## Number of observations violating
##   - 2-anonymity: 0 (0.000%) | in original data: 1257 (5.028%)
##   - 3-anonymity: 0 (0.000%) | in original data: 2177 (8.708%)
##   - 5-anonymity: 0 (0.000%) | in original data: 3313 (13.252%)
## 
## ----------------------------------------------------------------------
</code></pre><p>This output confirms that 5-anonymity has been achieved (i.e, 0 observations violating 5-anonymity in transformed data). It also shows the amount of observations that violated <em>k</em>-anonymity in our raw data for easy comparison.</p>
<p>Another helpful risk metric to compute when re-assessing re-identification risk is global risk. Although we did not specify any thresholds for an acceptable global risk metric, it is still helpful to calculate global risk to see how much we reduced average re-identification risk of categorical variables with our SDC methods:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#900;font-weight:bold">print</span>(sdcobj_final, <span style="color:#d14">&#34;risk&#34;</span>)
</code></pre></div><pre><code>## Risk measures:
## 
## Number of observations with higher risk than the main part of the data: 
##   in modified data: 1943
##   in original data: 5395
## Expected number of re-identifications: 
##   in modified data: 862.81 (3.45 %)
##   in original data: 2774.21 (11.10 %)
</code></pre><p>The output shows that we did reduce average re-identification risk by about 7.5% by applying SDC methods. Our final, de-identified data set still has quite a high global risk (3.45%) indicating that, on average, an intruder could successfully identify about 863 students if they were motivated enough. Depending on the type of data release, this could still be considered acceptable (e.g., restricted-use file with data sharing agreement/restrictions) if you can assume that a &ldquo;reasonable person&rdquo; under the FERPA guidelines will not be a highly motivated intruder (for more information on intruder testing see this 
<a href="https://www.ons.gov.uk/methodology/methodologytopicsandstatisticalconcepts/disclosurecontrol/guidanceonintrudertesting" target="_blank" rel="noopener">brief report</a> from the Office for National Statistics). However, if global risk is considered too high still, more SDC methods could be applied or other restrictions could be stipulated (e.g., data access, destruction, storage, etc.).</p>




<h3 id="continuous-variables-1">Continuous Variables
  <a href="#continuous-variables-1"><svg class="anchor-symbol" aria-hidden="true" height="26" width="26" viewBox="0 0 22 22" xmlns="http://www.w3.org/2000/svg">
      <path d="M0 0h24v24H0z" fill="currentColor"></path>
      <path d="M3.9 12c0-1.71 1.39-3.1 3.1-3.1h4V7H7c-2.76.0-5 2.24-5 5s2.24 5 5 5h4v-1.9H7c-1.71.0-3.1-1.39-3.1-3.1zM8 13h8v-2H8v2zm9-6h-4v1.9h4c1.71.0 3.1 1.39 3.1 3.1s-1.39 3.1-3.1 3.1h-4V17h4c2.76.0 5-2.24 5-5s-2.24-5-5-5z"></path>
    </svg></a>
</h3>
<p>To re-assess risk of continuous variables, we can confirm that all outliers (e.g., values past our thresholds for continuous variables) have been adequately protected by looking at frequency tables. We did this above when first recoding <code>gpa</code> to make sure our code was operating as expected. We can use the same tables to make sure outliers are protected. Let&rsquo;s check <code>iss_off</code> this time:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#998;font-style:italic">#Manipulated data</span>
<span style="color:#900;font-weight:bold">table</span>(sdcobj_final<span style="color:#000;font-weight:bold">@</span>manipNumVars<span style="color:#000;font-weight:bold">$</span>iss_off)
</code></pre></div><table class="table" style="width: auto !important; ">
 <thead>
  <tr>
   <th style="text-align:right;"> 0 </th>
   <th style="text-align:right;"> 1 </th>
   <th style="text-align:right;"> 2 </th>
   <th style="text-align:right;"> 3 </th>
   <th style="text-align:right;"> 4 </th>
   <th style="text-align:right;"> 5 </th>
   <th style="text-align:right;"> 6 </th>
   <th style="text-align:right;"> 7 </th>
   <th style="text-align:right;"> 8 </th>
   <th style="text-align:right;"> 9 </th>
   <th style="text-align:right;"> 10 </th>
   <th style="text-align:right;"> 11 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 21500 </td>
   <td style="text-align:right;"> 1151 </td>
   <td style="text-align:right;"> 454 </td>
   <td style="text-align:right;"> 225 </td>
   <td style="text-align:right;"> 168 </td>
   <td style="text-align:right;"> 100 </td>
   <td style="text-align:right;"> 89 </td>
   <td style="text-align:right;"> 49 </td>
   <td style="text-align:right;"> 18 </td>
   <td style="text-align:right;"> 30 </td>
   <td style="text-align:right;"> 16 </td>
   <td style="text-align:right;"> 80 </td>
  </tr>
</tbody>
</table>
<p>This looks good! There are no values outside our thresholds for continuous variables (e.g., protect top 1% and cell sizes under 10). If desired, you can also compare histograms between the raw and transformed data, however, I find it more useful to look at the exact values in the table. In practice, you will want to check frequency tables for all continuous variables.</p>
<p>If direct matching (e.g., ability to link variable other data based on the response) is a disclosure risk concern, it may also be helpful to look at cross/multi-tab frequency counts by student demographics with similar thresholds in mind or calculate distance-based risk metrics for these continuous variables.</p>




<h4 id="a-posteriori-risk-measures">A Posteriori Risk Measures
  <a href="#a-posteriori-risk-measures"></a>
</h4>
<p>The two distance-based risk metrics calculated in <code>{sdcMicro}</code>, record linkage and interval measure, are more applicable for perturbative SDC methods in which all continuous values have been altered. Record linkage calculates the number of exact matches between original and transformed values (i.e., when original and transformed values are the same). Interval measures calculate the amount of observations that are outside a specified interval around the transformed values. Both metrics compare all transformed values to the original values. Since we used non-perturbative methods and only transformed the outliers of continuous variables, these metrics will be overestimated (i.e., the majority of values will match the original values) and not as useful.</p>
<p>Distance-based risk metrics are most useful when it is possible to exactly match values of a continuous variables with a person&rsquo;s identity or public registries with potentially identifiable information (e.g., voter registration). Further, if exact matching is a disclosure concern (more info 
<a href="https://readthedocs.org/projects/sdcpractice/downloads/pdf/latest/" target="_blank" rel="noopener">here</a> pg.26), other SDC methods may need to be used (e.g., perturbative methods or including the continuous variable in <em>k</em>-anonymity assessment) to adequately protect privacy and fully de-identify the data set.</p>
<p>We assumed that direct matching is not a disclosure risk concern when we decided that top/bottom coding could be used to protect all continuous variables. This means we think it is highly unlikely that a &ldquo;reasonable person&rdquo; will know or be able to match the exact number of discipline offenses for a student since those data are not publicly reported - which seems to be a reasonable assumption for our variables. Thus, we will not calculate distance-based risk measures.</p>
<p>If you want more information about perturbative methods, calculating distance-based risk measures, or SDC in general I would recommend the 
<a href="https://readthedocs.org/projects/sdcpractice/downloads/pdf/latest/" target="_blank" rel="noopener">guide</a> referenced above or Matthias Templ&rsquo;s 
<a href="https://www.researchgate.net/publication/316991381_Statistical_Disclosure_Control_for_Microdata_Methods_and_Applications_in_R" target="_blank" rel="noopener">book</a>. Both implement SDC methods in R and utilize <code>{sdcMicro}</code> when applicable.</p>




<h3 id="data-utility">Data Utility
  <a href="#data-utility"><svg class="anchor-symbol" aria-hidden="true" height="26" width="26" viewBox="0 0 22 22" xmlns="http://www.w3.org/2000/svg">
      <path d="M0 0h24v24H0z" fill="currentColor"></path>
      <path d="M3.9 12c0-1.71 1.39-3.1 3.1-3.1h4V7H7c-2.76.0-5 2.24-5 5s2.24 5 5 5h4v-1.9H7c-1.71.0-3.1-1.39-3.1-3.1zM8 13h8v-2H8v2zm9-6h-4v1.9h4c1.71.0 3.1 1.39 3.1 3.1s-1.39 3.1-3.1 3.1h-4V17h4c2.76.0 5-2.24 5-5s-2.24-5-5-5z"></path>
    </svg></a>
</h3>
<p>As you may have already noticed, SDC is a balance between protecting disclosure risk and maintaining data utility. Those using SDC methods should aim to decrease re-identification risk to an acceptable level while reducing information loss. Transformed data needs to remain useful for data analysis and produce valid results during analysis. To determine the right balance of utility and risk, it is necessary to measure the usefulness of the data after SDC methods have been applied.</p>
<p>Similar to deciding which risk metrics and SDC methods to use, deciding on how to measure data utility can be a complicated process. To adequately measure data utility, it is necessary to understand the end goal and users of the data set to determine which information is most important to preserve. The data set that we have been working with for this tutorial was generated to reproduce the distributions of risk in common administrative student data and does not have any analytic use or end users. Thus, it does not seem appropriate to measure the utility of this data set.</p>
<p>In practice, there are many different ways to measure data utility after de-identification:</p>
<ul>
<li>
<p>Amount of missingness</p>
</li>
<li>
<p>Number of responses modified</p>
</li>
<li>
<p>Information loss/Eigenvalues (calculated in <code>{sdcMicro}</code>)</p>
</li>
<li>
<p>Comparing contingency tables</p>
</li>
<li>
<p>Comparing descriptive statistics</p>
</li>
</ul>
<p>Once you understand the intended goal of the data set, it is important to run statistical tests to make sure the conclusions from the transformed data are similar enough to those in the original data (e.g., correlations, regressions, etc.). Further, if any benchmark indicators (e.g., GINI index) or other important variables exist, it is also best to make sure these remain similar to the original values. More information can be found 
<a href="https://sdcpractice.readthedocs.io/en/latest/utility.html#" target="_blank" rel="noopener">here</a>. It is helpful to understand how the data will be used before beginning the SDC process since it can guide the decisions you make when deciding how to recode or transform variables.</p>
<p>If after assessing data utility you determine the utility is too low, you may want to rethink the disclosure risk thresholds, type of release, or SDC methods used. It is also important to explain the results to the relevant collaborators (e.g., data provider, PI, end users, legal experts, etc.) to determine the best way to increase data utility while still adequately de-identifying the data set.</p>

        
        


      </section>
      <footer class="post-footer">
   
    

  
</footer>

    </article>
    
      
<div class="post-comments pa0 pa4-l mt4">
  
  <script src="https://utteranc.es/client.js"
          repo="hugo-apero/apero"
          issue-term="pathname"
          theme="boxy-light"
          label="comments :crystal_ball:"
          crossorigin="anonymous"
          async
          type="text/javascript">
  </script>
  
</div>

    
  </section>
</main>
<footer class="site-footer pv4 bt b--transparent ph5" role="contentinfo">
  <nav class="db dt-l w-100">
    <p class="site-copyright f7 db dtc-l v-mid w-100 w-33-l tc tl-l pv2 pv0-l mv0 lh-copy">
      &copy; 2024 RStudio, Anywhere
      <br />
      
Based on <span xmlns:dct="http://purl.org/dc/terms/" property="dct:title"><a xmlns:dct="http://purl.org/dc/terms/" href="https://github.com/formspree/blogophonic-hugo" rel="dct:source">Blogophonic</a></span> by <a xmlns:cc="http://creativecommons.org/ns#" href="https://formspree.io" property="cc:attributionName" rel="cc:attributionURL">Formspree</a>.
    </p>
    
      
    
    <div class="site-links f6 db dtc-l v-mid w-100 w-67-l tc tr-l pv2 pv0-l mv0">
      
    </div>
  </nav>
</footer>

      </div>
    </body>
</html>
